import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
L10N = ROOT / "lib" / "l10n"

en_template = json.load(open(L10N / "app_en.arb", encoding="utf-8"))

# Load audio/karaoke translations
from update_arbs import AUDIO_KARAOKE_TRANSLATIONS

# Dictionary of translations for keys that were identical to EN in the priority languages:
# zh, zh_TW, hi, th, si, my

PRIORITY_TRANSLATIONS = {
    "zh": {
        "appName": "阿毗达摩",
        "appTagline": "阿毗达摩藏",
        "initializing": "正在初始化…",
        "loadingDoctrineData": "正在加载并校验法数数据…",
        "loadingTakingLonger": "启动时间长于预期。可能正在为您的设备优化数据。",
        "unknownError": "未知错误",
        "dataError": "数据错误",
        "invalidData": "数据无效",
        "invalidDataDescription": "系统检测到法数校验规则冲突。请联系编辑团队审查数据。",
        "errorWithMessage": "错误: {message}",
        "holdGlobeToReset": "长按地球图标3秒可恢复系统语言",
        "restoredSystemLanguage": "已恢复系统语言",
        "screenReaderHints": "屏幕阅读器提示",
        "textScale": "文字缩放",
        "onboardingVisualTitle": "清晰洞见",
        "onboardingVisualSubtitle": "心与心所矩阵",
        "onboardingVisualBody": "在交互式矩阵中探索121种心和52种心所。色彩、形状与文字清晰标示每种相应关系。",
        "onboardingCausalityTitle": "深刻理解",
        "onboardingCausalitySubtitle": "十二缘起",
        "onboardingCausalityBody": "通过互联的学习视角探索十二缘起支与业的分类法。",
        "onboardingExploreTitle": "自主探索",
        "onboardingExploreSubtitle": "非线性学习路径",
        "onboardingExploreBody": "自由选择十个相互关联的修学单元。主动回忆、测验与复习助您稳固法义。",
        "beginExploring": "开始探索",
        "matrixSemantics": "阿毗达摩矩阵，显示 {count} 种心",
        "clearSearch": "清除搜索",
        "dataWarningsCount": "{count} 个数据警告",
        "dataWarningTitle": "数据警告",
        "defilements": "烦恼",
        "relatedDhammas": "相关法",
        "kammaTitle": "业 (Kamma)",
        "paliLabel": "巴利语:",
        "stopPronunciation": "停止发音",
        "listenPaliPronunciation": "聆听巴利语发音",
        "ttsUnavailable": "此设备不支持语音合成。",
        "dragHandleSemantics": "拖动以调整大小",
        "cittaNumber": "第 {number} 心",
        "doctrine": "教理说明",
        "examples": "例子",
        "fixedCetasikasCount": "固定心所 ({count})",
        "variableCetasikasCount": "不固定心所 ({count})",
        "personalNote": "个人笔记",
        "personalNoteHint": "输入您的笔记…",
        "wholesome": "善",
        "functional": "唯作",
        "pleasantFeeling": "乐受",
        "unpleasantFeeling": "苦受",
        "neutralFeeling": "舍受",
        "joyfulFeeling": "喜受",
        "alwaysAssociated": "必定相应",
        "mayBeAssociated": "可能相应",
        "fourfoldDefinition": "四种特相 (特相/作用/现起/近因)",
        "characteristic": "特相 (Lakkhaṇa)",
        "functionLabel": "作用 (Rasa)",
        "manifestation": "现起 (Paccupaṭṭhāna)",
        "proximateCause": "近因 (Padaṭṭhāna)",
        "doctrinalConflicts": "教理相违心所",
        "rulesCount": "{count} 条规则",
        "universalCetasikas": "7 通一切心心所",
        "occasionalCetasikas": "6 杂心所",
        "unwholesomeCetasikas": "14 不善心所",
        "beautifulCetasikas": "25 美心所",
        "rowCittaSemantics": "第 {displayIndex} 行心: {name}; 典籍编号 {order}; 分组 {group}; 感受 {feeling}。{action}",
        "cetasikaSemantics": "心所 {name} ({pali})，分组 {group}。{state} 点击查看详情。",
        "matrixCornerSemantics": "矩阵角: 行代表心，列代表心所",
        "associationSemantics": "{association}: 心 {cittaId} 与 心所 {cetasikaId}",
        "savedItemsCount": "{count} 个已保存项目",
        "cittaTab": "心",
        "cetasikaTab": "心所",
        "notesTab": "笔记",
        "noBookmarkedCittas": "暂无收藏的心",
        "bookmarkCittaHint": "打开修学课程并点击书签图标以保存",
        "loadingCittas": "正在加载心的数据…",
        "noBookmarkedCetasikas": "暂无收藏的心所",
        "loadingCetasikas": "正在加载心所数据…",
        "noNotes": "暂无笔记",
        "addNoteHint": "在修学中点击编辑图标添加个人笔记",
        "deleteNoteQuestion": "删除笔记？",
        "deleteNoteWarning": "此笔记将被永久删除。您确定吗？",
        "addNote": "添加笔记",
        "removeBookmark": "移除书签",
        "editNote": "编辑笔记",
        "deleteNote": "删除笔记",
        "noteUpdated": "笔记已更新",
        "noteSaved": "笔记已保存",
        "editNoteTitle": "编辑笔记",
        "addNoteTitle": "添加笔记",
        "studyNoteHint": "写下您关于此项的修学体会…\n\n例如：此心在禅修中生起于…",
        "charactersCount": "{current} / {maximum} 字符",
        "update": "更新",
        "saveNote": "保存笔记",
        "studyProgressPercent": "修学进度: {percent}%",
        "modulesCompletedShort": "已完成\n单元",
        "recommendedNext": "推荐下一单元",
        "progressOverview": "修学进度概览",
        "totalModules": "单元总数",
        "dueForReview": "待复习",
        "moduleHasNoData": "此单元暂无心/心所数据。请检查JSON数据。",
        "cittasInModule": "本单元包含的心 — {count}",
        "cetasikasInModule": "本单元包含的心所 — {count}",
        "reviewCetasikaQuestion": "心所 “{name}” ({pali}) 的含义是什么？",
        "groupAnswer": "分组: {group}",
        "reviewCittaQuestion": "心 “{name}” 属于哪个界，伴随何种感受？",
        "cittaReviewAnswer": "界: {sphere}\n感受: {feeling}\n巴利语: {pali}",
        "noReviewContent": "此单元暂无复习内容。请稍后查看。",
        "reviewedCount": "{revealed} / {total} 已复习",
        "reviewComplete": "您已复习全部内容。快来通过测验检验理解吧。",
        "tapToReveal": "点击显示答案",
        "answerLabel": "答案: {answer}",
        "revealAnswer": "显示答案",
        "moduleQuizTitle": "测验\n{module}",
        "moduleContentCount": "本单元共 {count} 个知识点",
        "quizMaximumDescription": "涵盖本单元的最多10道单项选择题",
        "startQuiz": "开始测验",
        "cittasCount": "{count} 种心",
        "cetasikasCount": "{count} 种心所",
        "noteForItem": "笔记: {name}",
        "quizLevelDescription": "每个级别从本单元生成最多 {count} 道题目",
        "insufficientQuizData": "本单元数据不足以生成题目。",
        "correctAnswers": "{score} / {total} 正确",
        "quizExcellent": "太棒了！您已掌握本单元内容。",
        "quizTryAgain": "请温习课程内容后重试。",
        "quizInsufficientDataMessage": "单元 “{module}” 数据不足以生成题目。",
        "quizTypeCetasikaGroup": "心所分类",
        "quizTypeFeeling": "感受辨识",
        "quizTypeConflict": "教理相违",
        "quizTypeSphere": "界 (Sphere)",
        "beginnerDescription": "基础心所分组与感受",
        "intermediateDescription": "包含心所相违规则",
        "advancedDescription": "包含界分类及所有题型",
        "trueLabel": "正确",
        "falseLabel": "错误",
        "trueOrFalse": "对还是错？",
        "quizCetasikaGroupQuestion": "“{name}” ({pali}) 属于哪个心所分组？",
        "quizCetasikaGroupExplanation": "“{name}” 属于 {group}。\n{description}",
        "quizCetasikaClaim": "“{name}” ({pali}) 属于 {group}。对还是错？",
        "quizCittaFeelingQuestion": "心 “{name}” 伴随何种感受？",
        "quizCittaFeelingExplanation": "“{name}” 伴随 {feeling}。",
        "quizCittaFeelingClaim": "心 “{name}” 伴随 {feeling}。对还是错？",
        "conflictNo": "否 — 彼此相违",
        "conflictAlwaysYes": "是 — 恒常俱起",
        "conflictSometimesYes": "是 — 有时俱起",
        "quizConflictQuestion": "“{first}” 和 “{second}” 能否在同一个心中同起？",
        "quizSphereQuestion": "心 “{name}” 属于哪个界？",
        "quizSphereExplanation": "“{name}” 属于 {sphere}。",
        "quizSphereClaim": "心 “{name}” 属于 {sphere}。对还是错？",
        "phaseFoundation": "第一阶段 — 基础",
        "phaseCausality": "第二阶段 — 因果",
        "phaseMastery": "第三阶段 — 通达",
        "continueListening": "继续聆听",
        "audioBackgroundLimit": "后台音频播放取决于系统已安装的语音引擎"
    },
    "zh_TW": {
        "appName": "阿毗達摩",
        "appTagline": "阿毗達摩藏",
        "initializing": "正在初始化…",
        "loadingDoctrineData": "正在加載並校驗法數數據…",
        "loadingTakingLonger": "啟動時間長於預期。可能正在為您的設備優化數據。",
        "unknownError": "未知錯誤",
        "dataError": "數據錯誤",
        "invalidData": "數據無效",
        "invalidDataDescription": "系統檢測到法數校驗規則衝突。請聯繫編輯團隊審查數據。",
        "errorWithMessage": "錯誤: {message}",
        "holdGlobeToReset": "長按地球圖標3秒可恢復系統語言",
        "restoredSystemLanguage": "已恢復系統語言",
        "screenReaderHints": "螢幕閱讀器提示",
        "textScale": "文字縮放",
        "onboardingVisualTitle": "清晰洞見",
        "onboardingVisualSubtitle": "心與心所矩陣",
        "onboardingVisualBody": "在互動式矩陣中探索121種心和52種心所。色彩、形狀與文字清晰標示每種相應關係。",
        "onboardingCausalityTitle": "深刻理解",
        "onboardingCausalitySubtitle": "十二緣起",
        "onboardingCausalityBody": "透過互聯的學習視角探索十二緣起支與業的分類法。",
        "onboardingExploreTitle": "自主探索",
        "onboardingExploreSubtitle": "非線性學習路徑",
        "onboardingExploreBody": "自由選擇十個相互關聯的修學單元。主動回憶、測驗與複習助您穩固法義。",
        "beginExploring": "開始探索",
        "matrixSemantics": "阿毗達摩矩陣，顯示 {count} 種心",
        "clearSearch": "清除搜尋",
        "dataWarningsCount": "{count} 個數據警告",
        "dataWarningTitle": "數據警告",
        "defilements": "煩惱",
        "relatedDhammas": "相關法",
        "kammaTitle": "業 (Kamma)",
        "paliLabel": "巴利語:",
        "stopPronunciation": "停止發音",
        "listenPaliPronunciation": "聆聽巴利語發音",
        "ttsUnavailable": "此設備不支援語音合成。",
        "dragHandleSemantics": "拖動以調整大小",
        "cittaNumber": "第 {number} 心",
        "doctrine": "教理說明",
        "examples": "例子",
        "fixedCetasikasCount": "固定心所 ({count})",
        "variableCetasikasCount": "不固定心所 ({count})",
        "personalNote": "個人筆記",
        "personalNoteHint": "輸入您的筆記…",
        "wholesome": "善",
        "functional": "唯作",
        "pleasantFeeling": "樂受",
        "unpleasantFeeling": "苦受",
        "neutralFeeling": "捨受",
        "joyfulFeeling": "喜受",
        "alwaysAssociated": "必定相應",
        "mayBeAssociated": "可能相應",
        "fourfoldDefinition": "四種特相 (特相/作用/現起/近因)",
        "characteristic": "特相 (Lakkhaṇa)",
        "functionLabel": "作用 (Rasa)",
        "manifestation": "現起 (Paccupaṭṭhāna)",
        "proximateCause": "近因 (Padaṭṭhāna)",
        "doctrinalConflicts": "教理相違心所",
        "rulesCount": "{count} 條規則",
        "universalCetasikas": "7 通一切心心所",
        "occasionalCetasikas": "6 雜心所",
        "unwholesomeCetasikas": "14 不善心所",
        "beautifulCetasikas": "25 美心所",
        "rowCittaSemantics": "第 {displayIndex} 行心: {name}; 典籍編號 {order}; 分組 {group}; 感受 {feeling}。{action}",
        "cetasikaSemantics": "心所 {name} ({pali})，分組 {group}。{state} 點擊查看詳情。",
        "matrixCornerSemantics": "矩陣角: 行代表心，列代表心所",
        "associationSemantics": "{association}: 心 {cittaId} 與 心所 {cetasikaId}",
        "savedItemsCount": "{count} 個已保存項目",
        "cittaTab": "心",
        "cetasikaTab": "心所",
        "notesTab": "筆記",
        "noBookmarkedCittas": "暫無收藏的心",
        "bookmarkCittaHint": "打開修學課程並點擊書籤圖標以保存",
        "loadingCittas": "正在加載心的數據…",
        "noBookmarkedCetasikas": "暫無收藏的心所",
        "loadingCetasikas": "正在加載心所數據…",
        "noNotes": "暫無筆記",
        "addNoteHint": "在修學中點擊編輯圖標添加個人筆記",
        "deleteNoteQuestion": "刪除筆記？",
        "deleteNoteWarning": "此筆記將被永久刪除。您確定嗎？",
        "addNote": "添加筆記",
        "removeBookmark": "移除書籤",
        "editNote": "編輯筆記",
        "deleteNote": "刪除筆記",
        "noteUpdated": "筆記已更新",
        "noteSaved": "筆記已保存",
        "editNoteTitle": "編輯筆記",
        "addNoteTitle": "添加筆記",
        "studyNoteHint": "寫下您關於此項的修學體會…\n\n例如：此心在禪修中生起於…",
        "charactersCount": "{current} / {maximum} 字符",
        "update": "更新",
        "saveNote": "保存筆記",
        "studyProgressPercent": "修學進度: {percent}%",
        "modulesCompletedShort": "已完成\n單元",
        "recommendedNext": "推薦下一單元",
        "progressOverview": "修學進度概覽",
        "totalModules": "單元總數",
        "dueForReview": "待複習",
        "moduleHasNoData": "此單元暫無心/心所數據。請檢查JSON數據。",
        "cittasInModule": "本單元包含的心 — {count}",
        "cetasikasInModule": "本單元包含的心所 — {count}",
        "reviewCetasikaQuestion": "心所 “{name}” ({pali}) 的含義是什麼？",
        "groupAnswer": "分組: {group}",
        "reviewCittaQuestion": "心 “{name}” 屬於哪個界，伴隨何種感受？",
        "cittaReviewAnswer": "界: {sphere}\n感受: {feeling}\n巴利語: {pali}",
        "noReviewContent": "此單元暫無複習內容。請稍後查看。",
        "reviewedCount": "{revealed} / {total} 已複習",
        "reviewComplete": "您已複習全部內容。快來透過測驗檢驗理解吧。",
        "tapToReveal": "點擊顯示答案",
        "answerLabel": "答案: {answer}",
        "revealAnswer": "顯示答案",
        "moduleQuizTitle": "測驗\n{module}",
        "moduleContentCount": "本單元共 {count} 個知識點",
        "quizMaximumDescription": "涵蓋本單元的最多10道單項選擇題",
        "startQuiz": "開始測驗",
        "cittasCount": "{count} 種心",
        "cetasikasCount": "{count} 種心所",
        "noteForItem": "筆記: {name}",
        "quizLevelDescription": "每個級別從本單元生成最多 {count} 道題目",
        "insufficientQuizData": "本單元數據不足以生成題目。",
        "correctAnswers": "{score} / {total} 正確",
        "quizExcellent": "太棒了！您已掌握本單元內容。",
        "quizTryAgain": "請溫習課程內容後重試。",
        "quizInsufficientDataMessage": "單元 “{module}” 數據不足以生成題目。",
        "quizTypeCetasikaGroup": "心所分類",
        "quizTypeFeeling": "感受辨識",
        "quizTypeConflict": "教理相違",
        "quizTypeSphere": "界 (Sphere)",
        "beginnerDescription": "基礎心所分組與感受",
        "intermediateDescription": "包含心所相違規則",
        "advancedDescription": "包含界分類及所有題型",
        "trueLabel": "正確",
        "falseLabel": "錯誤",
        "trueOrFalse": "對還是錯？",
        "quizCetasikaGroupQuestion": "“{name}” ({pali}) 屬於哪個心所分組？",
        "quizCetasikaGroupExplanation": "“{name}” 屬於 {group}。\n{description}",
        "quizCetasikaClaim": "“{name}” ({pali}) 屬於 {group}。對還是錯？",
        "quizCittaFeelingQuestion": "心 “{name}” 伴隨何種感受？",
        "quizCittaFeelingExplanation": "“{name}” 伴隨 {feeling}。",
        "quizCittaFeelingClaim": "心 “{name}” 伴随 {feeling}。對還是錯？",
        "conflictNo": "否 — 彼此相違",
        "conflictAlwaysYes": "是 — 恆常俱起",
        "conflictSometimesYes": "是 — 有時俱起",
        "quizConflictQuestion": "“{first}” 和 “{second}” 能否在同一個心中同起？",
        "quizSphereQuestion": "心 “{name}” 屬於哪個界？",
        "quizSphereExplanation": "“{name}” 屬於 {sphere}。",
        "quizSphereClaim": "心 “{name}” 屬於 {sphere}。對還是錯？",
        "phaseFoundation": "第一階段 — 基礎",
        "phaseCausality": "第二階段 — 因果",
        "phaseMastery": "第三階段 — 通達",
        "continueListening": "繼續聆聽",
        "audioBackgroundLimit": "後台音頻播放取決於系統已安裝的語音引擎"
    },
    "hi": {
        "appName": "अभिधम्म",
        "appTagline": "अभिधम्मपिटक",
        "initializing": "आरंभ हो रहा है…",
        "loadingDoctrineData": "धम्म डेटा लोड और मान्य किया जा रहा है…",
        "loadingTakingLonger": "प्रारंभ होने में अपेक्षा से अधिक समय लग रहा है। डेटा अनुकूलित किया जा रहा हो सकता है।",
        "unknownError": "अज्ञात त्रुटि",
        "dataError": "डेटा त्रुटि",
        "invalidData": "अमान्य डेटा",
        "invalidDataDescription": "सिस्टम ने धम्म सत्यापन नियमों का उल्लंघन पाया है। कृपया डेटा की समीक्षा के लिए संपर्क करें।",
        "errorWithMessage": "त्रुटि: {message}",
        "holdGlobeToReset": "सिस्टम भाषा पुनर्स्थापित करने के लिए ग्लोब को 3 सेकंड तक दबाकर रखें",
        "restoredSystemLanguage": "सिस्टम भाषा पुनर्स्थापित की गई",
        "screenReaderHints": "स्क्रीन रीडर संकेत",
        "textScale": "पाठ का आकार",
        "onboardingVisualTitle": "स्पष्ट दर्शन",
        "onboardingVisualSubtitle": "चित्त × चेतसिक मैट्रिक्स",
        "onboardingVisualBody": "121 चित्त और 52 चेतसिकों को एक इंटरैक्टिव मैट्रिक्स में जानें। रंग, आकार और शब्द प्रत्येक संयोजन को सुगम बनाते हैं।",
        "onboardingCausalityTitle": "गहन बोध",
        "onboardingCausalitySubtitle": "प्रतीत्यसमुत्पाद",
        "onboardingCausalityBody": "प्रतीत्यसमुत्पाद के बारह अंगों और कर्म के वर्गीकरण को अंतर्संबंधित दृष्टिकोण से समझें।",
        "onboardingExploreTitle": "स्वयं खोजें",
        "onboardingExploreSubtitle": "गैर-रैखिक अध्ययन मार्ग",
        "onboardingExploreBody": "दस जुड़े हुए मॉड्यूल के माध्यम से अपना मार्ग चुनें। स्मरण, प्रश्नोत्तरी और पुनरावलोकन ज्ञान को स्थिर करते हैं।",
        "beginExploring": "अन्वेषण आरंभ करें",
        "matrixSemantics": "अभिधम्म मैट्रिक्स {count} चित्त दिखा रहा है",
        "clearSearch": "खोज साफ़ करें",
        "dataWarningsCount": "{count} डेटा चेतावनियाँ",
        "dataWarningTitle": "डेटा चेतावनी",
        "defilements": "क्लेश (Kilesa)",
        "relatedDhammas": "संबंधित धर्म",
        "kammaTitle": "कर्म (Kamma)",
        "paliLabel": "पाळि:",
        "stopPronunciation": "उच्चारण रोकें",
        "listenPaliPronunciation": "पाळि उच्चारण सुनें",
        "ttsUnavailable": "इस डिवाइस पर वाक् संश्लेषण समर्थित नहीं है।",
        "dragHandleSemantics": "आकार बदलने के लिए खींचें",
        "cittaNumber": "चित्त {number}",
        "doctrine": "धम्म व्याख्या",
        "examples": "उदाहरण",
        "fixedCetasikasCount": "अपरिवर्तनीय चेतसिक ({count})",
        "variableCetasikasCount": "परिवर्तनीय चेतसिक ({count})",
        "personalNote": "व्यक्तिगत टिप्पणी",
        "personalNoteHint": "अपनी टिप्पणी दर्ज करें…",
        "wholesome": "कुशल",
        "functional": "क्रिया",
        "pleasantFeeling": "सुख वेदना (शारीरिक)",
        "unpleasantFeeling": "दुःख वेदना (शारीरिक)",
        "neutralFeeling": "उपेक्षा वेदना",
        "joyfulFeeling": "सोमनस्स वेदना (मानसिक)",
        "alwaysAssociated": "सदैव संयुक्त",
        "mayBeAssociated": "कदाचित संयुक्त",
        "fourfoldDefinition": "चतुर्विध लक्षण (लक्षण/कृत्य/उपस्थिति/पदट्ठान)",
        "characteristic": "लक्षण (Lakkhaṇa)",
        "functionLabel": "कृत्य / रस (Rasa)",
        "manifestation": "पच्चुपट्ठान (Paccupaṭṭhāna)",
        "proximateCause": "पदट्ठान / निकट कारण (Padaṭṭhāna)",
        "doctrinalConflicts": "सैद्धांतिक विरोध",
        "rulesCount": "{count} नियम",
        "universalCetasikas": "7 सर्वचित्तसाधारण",
        "occasionalCetasikas": "6 प्रकीर्णक",
        "unwholesomeCetasikas": "14 अकुशल",
        "beautifulCetasikas": "25 शोभन",
        "rowCittaSemantics": "चित्त पंक्ति {displayIndex}: {name}; विहित संख्या {order}; वर्ग {group}; वेदना {feeling}। {action}",
        "cetasikaSemantics": "चेतसिक {name} ({pali}), वर्ग {group}। {state} विवरण के लिए टैप करें।",
        "matrixCornerSemantics": "मैट्रिक्स कोना: पंक्तियाँ चित्त हैं और स्तंभ चेतसिक",
        "associationSemantics": "{association}: चित्त {cittaId} चेतसिक {cetasikaId} के साथ",
        "savedItemsCount": "{count} सहेजे गए विषय",
        "cittaTab": "चित्त",
        "cetasikaTab": "चेतसिक",
        "notesTab": "टिप्पणियाँ",
        "noBookmarkedCittas": "कोई बुकमार्क किया गया चित्त नहीं",
        "bookmarkCittaHint": "पाठ खोलें और सहेजने के लिए बुकमार्क आइकन पर टैप करें",
        "loadingCittas": "चित्त लोड हो रहे हैं…",
        "noBookmarkedCetasikas": "कोई बुकमार्क किया गया चेतसिक नहीं",
        "loadingCetasikas": "चेतसिक लोड हो रहे हैं…",
        "noNotes": "अभी तक कोई टिप्पणी नहीं",
        "addNoteHint": "व्यक्तिगत टिप्पणी जोड़ने के लिए पाठ में संपादन आइकन टैप करें",
        "deleteNoteQuestion": "टिप्पणी हटाएं?",
        "deleteNoteWarning": "यह टिप्पणी स्थायी रूप से हटा दी जाएगी। क्या आप सुनिश्चित हैं?",
        "addNote": "टिप्पणी जोड़ें",
        "removeBookmark": "बुकमार्क हटाएं",
        "editNote": "टिप्पणी संपादित करें",
        "deleteNote": "टिप्पणी हटाएं",
        "noteUpdated": "टिप्पणी अद्यतित की गई",
        "noteSaved": "टिप्पणी सहेजी गई",
        "editNoteTitle": "टिप्पणी संपादित करें",
        "addNoteTitle": "टिप्पणी जोड़ें",
        "studyNoteHint": "इस विषय पर अपनी टिप्पणी लिखें…\n\nउदाहरण: यह चित्त ध्यान के दौरान तब उत्पन्न होता है जब…",
        "charactersCount": "{current} / {maximum} वर्ण",
        "update": "अद्यतन करें",
        "saveNote": "टिप्पणी सहेजें",
        "studyProgressPercent": "अध्ययन प्रगति: {percent}%",
        "modulesCompletedShort": "मॉड्यूल\nपूर्ण",
        "recommendedNext": "अनुशंसित अगला",
        "progressOverview": "प्रगति अवलोकन",
        "totalModules": "कुल मॉड्यूल",
        "dueForReview": "पुनरावलोकन हेतु",
        "moduleHasNoData": "इस मॉड्यूल में चित्त/चेतसिक डेटा नहीं है। कृपया JSON डेटा जांचें।",
        "cittasInModule": "इस मॉड्यूल में चित्त — {count}",
        "cetasikasInModule": "इस मॉड्यूल में चेतसिक — {count}",
        "reviewCetasikaQuestion": "चेतसिक “{name}” ({pali}) का क्या अर्थ है?",
        "groupAnswer": "वर्ग: {group}",
        "reviewCittaQuestion": "चित्त “{name}” किस भूमि और वेदना से युक्त है?",
        "cittaReviewAnswer": "भूमि: {sphere}\nवेदना: {feeling}\nपाळि: {pali}",
        "noReviewContent": "इस मॉड्यूल में अभी कोई पुनरावलोकन सामग्री नहीं है। कृपया बाद में देखें।",
        "reviewedCount": "{revealed} / {total} पुनरावलोकित",
        "reviewComplete": "आपने पूरी सामग्री का पुनरावलोकन कर लिया है। अपनी समझ जांचने के लिए प्रश्नोत्तरी करें।",
        "tapToReveal": "उत्तर देखने के लिए टैप करें",
        "answerLabel": "उत्तर: {answer}",
        "revealAnswer": "उत्तर प्रकट करें",
        "moduleQuizTitle": "प्रश्नोत्तरी\n{module}",
        "moduleContentCount": "इस मॉड्यूल में {count} विषय",
        "quizMaximumDescription": "इस मॉड्यूल को कवर करने वाले 10 बहुविकल्पीय प्रश्न",
        "startQuiz": "प्रश्नोत्तरी आरंभ करें",
        "cittasCount": "{count} चित्त",
        "cetasikasCount": "{count} चेतसिक",
        "noteForItem": "टिप्पणी: {name}",
        "quizLevelDescription": "प्रत्येक स्तर इस मॉड्यूल से अधिकतम {count} प्रश्न उत्पन्न करता है",
        "insufficientQuizData": "इस मॉड्यूल में प्रश्न बनाने के लिए पर्याप्त डेटा नहीं है।",
        "correctAnswers": "{score} / {total} सही",
        "quizExcellent": "उत्कृष्ट! आपने इस मॉड्यूल में दक्षता प्राप्त कर ली है।",
        "quizTryAgain": "सामग्री की समीक्षा करें और पुनः प्रयास करें।",
        "quizInsufficientDataMessage": "मॉड्यूल “{module}” में प्रश्न बनाने के लिए पर्याप्त डेटा नहीं है।",
        "quizTypeCetasikaGroup": "चेतसिक वर्गीकरण",
        "quizTypeFeeling": "वेदना पहचान",
        "quizTypeConflict": "सैद्धांतिक विरोध",
        "quizTypeSphere": "भूमि / लोक",
        "beginnerDescription": "मूल चेतसिक वर्ग और वेदनाएं",
        "intermediateDescription": "चेतसिक विरोध नियम सम्मिलित",
        "advancedDescription": "सभी भूमियां और प्रश्न प्रकार सम्मिलित",
        "trueLabel": "सत्य",
        "falseLabel": "असत्य",
        "trueOrFalse": "सत्य या असत्य?",
        "quizCetasikaGroupQuestion": "“{name}” ({pali}) किस वर्ग में आता है?",
        "quizCetasikaGroupExplanation": "“{name}” {group} से संबंधित है।\n{description}",
        "quizCetasikaClaim": "“{name}” ({pali}) {group} से संबंधित है। सत्य या असत्य?",
        "quizCittaFeelingQuestion": "चित्त “{name}” के साथ कौन सी वेदना होती है?",
        "quizCittaFeelingExplanation": "“{name}” में {feeling} होती है।",
        "quizCittaFeelingClaim": "चित्त “{name}” में {feeling} होती है। सत्य या असत्य?",
        "conflictNo": "नहीं — वे परस्पर विरोधी हैं",
        "conflictAlwaysYes": "हाँ — वे सदैव साथ उत्पन्न होते हैं",
        "conflictSometimesYes": "हाँ — वे कभी-कभी साथ उत्पन्न होते हैं",
        "quizConflictQuestion": "क्या “{first}” और “{second}” एक ही चित्त में साथ उत्पन्न हो सकते हैं?",
        "quizSphereQuestion": "चित्त “{name}” किस भूमि से संबंधित है?",
        "quizSphereExplanation": "“{name}” {sphere} से संबंधित है।",
        "quizSphereClaim": "चित्त “{name}” {sphere} से संबंधित है। सत्य या असत्य?",
        "phaseFoundation": "चरण 1 — आधार",
        "phaseCausality": "चरण 2 — कार्य-कारण",
        "phaseMastery": "चरण 3 — दक्षता",
        "continueListening": "सुनना जारी रखें",
        "audioBackgroundLimit": "पृष्ठभूमि ऑडियो स्थापित वॉइस इंजन पर निर्भर करता है"
    },
    "th": {
        "appName": "พระอภิธรรม",
        "appTagline": "พระอภิธรรมปิฎก",
        "initializing": "กำลังเริ่มต้น…",
        "loadingDoctrineData": "กำลังโหลดและตรวจสอบข้อมูลพระธรรม…",
        "loadingTakingLonger": "การเริ่มต้นใช้เวลานานกว่าปกติ อาจกำลังปรับข้อมูลให้เหมาะสมกับอุปกรณ์",
        "unknownError": "ข้อผิดพลาดที่ไม่รู้จัก",
        "dataError": "ข้อผิดพลาดของข้อมูล",
        "invalidData": "ข้อมูลไม่ถูกต้อง",
        "invalidDataDescription": "ระบบตรวจพบความขัดแย้งของกฎการตรวจสอบธรรมะ โปรดติดต่อทีมงานเพื่อตรวจสอบ",
        "hide": "ซ่อน",
        "errorWithMessage": "ข้อผิดพลาด: {message}",
        "languageChangePreviewBody": "อินเทอร์เฟซจะเปลี่ยนเป็น {language}",
        "languageChangedTo": "เปลี่ยนภาษาเป็น {language} แล้ว",
        "holdGlobeToReset": "กดลูกโลกค้างไว้ 3 วินาทีเพื่อคืนค่าภาษาของระบบ",
        "restoredSystemLanguage": "คืนค่าภาษาของระบบแล้ว",
        "screenReaderHints": "คำแนะนำโปรแกรมอ่านหน้าจอ",
        "textScale": "ขนาดตัวอักษร",
        "onboardingVisualTitle": "เห็นอย่างแจ่มแจ้ง",
        "onboardingVisualSubtitle": "ตารางจิต × เจตสิก",
        "onboardingVisualBody": "สำรวจจิต 121 ดวงและเจตสิก 52 ดวงในตารางปฏิสัมพันธ์ สี รูปร่าง และข้อความระบุความสัมพันธ์อย่างชัดเจน",
        "onboardingCausalityTitle": "เข้าใจอย่างลึกซึ้ง",
        "onboardingCausalitySubtitle": "ปฏิจจสมุปบาท",
        "onboardingCausalityBody": "สำรวจองค์ประกอบ 12 ของปฏิจจสมุปบาทและการจำแนกกรรมผ่านมุมมองการเรียนรู้ที่เชื่อมโยงกัน",
        "onboardingExploreTitle": "ค้นพบด้วยตนเอง",
        "onboardingExploreSubtitle": "เส้นทางการศึกษาแบบไม่เป็นเส้นตรง",
        "onboardingExploreBody": "เลือกเส้นทางของคุณผ่าน 10 บทเรียนที่เชื่อมโยงกัน การทบทวนและแบบทดสอบช่วยให้ความรู้คงทน",
        "beginExploring": "เริ่มการสำรวจ",
        "matrixSemantics": "ตารางพระอภิธรรมแสดงจิต {count} ดวง",
        "clearSearch": "ล้างการค้นหา",
        "dataWarningsCount": "คำเตือนข้อมูล {count} รายการ",
        "dataWarningTitle": "คำเตือนข้อมูล",
        "defilements": "กิเลส",
        "relatedDhammas": "ธรรมที่เกี่ยวข้อง",
        "kammaTitle": "กรรม (Kamma)",
        "paliLabel": "บาลี:",
        "stopPronunciation": "หยุดการออกเสียง",
        "listenPaliPronunciation": "ฟังการออกเสียงภาษาบาลี",
        "ttsUnavailable": "อุปกรณ์นี้ไม่รองรับการสังเคราะห์เสียงพูด",
        "dragHandleSemantics": "ลากเพื่อปรับขนาด",
        "cittaNumber": "จิตที่ {number}",
        "doctrine": "คำอธิบายธรรม",
        "examples": "ตัวอย่าง",
        "fixedCetasikasCount": "เจตสิกที่แน่นอน ({count})",
        "variableCetasikasCount": "เจตสิกที่ไม่แน่นอน ({count})",
        "personalNote": "บันทึกส่วนตัว",
        "personalNoteHint": "พิมพ์บันทึกของคุณ…",
        "wholesome": "กุศล",
        "functional": "กิริยา",
        "pleasantFeeling": "สุขเวทนา (ทางกาย)",
        "unpleasantFeeling": "ทุกขเวทนา (ทางกาย)",
        "neutralFeeling": "อุเบกขาเวทนา",
        "joyfulFeeling": "โสมนัสสเวทนา (ทางใจ)",
        "alwaysAssociated": "ประกอบแน่นอน",
        "mayBeAssociated": "อาจประกอบร่วม",
        "fourfoldDefinition": "ลักขณาทิจตุกะ (ลักษณะ 4 ประการ)",
        "characteristic": "ลักษณะ (Lakkhaṇa)",
        "functionLabel": "กิจ (Rasa)",
        "manifestation": "อาการปรากฏ (Paccupaṭṭhāna)",
        "proximateCause": "เหตุใกล้ (Padaṭṭhāna)",
        "doctrinalConflicts": "เจตสิกที่เป็นปฏิปักษ์กัน",
        "rulesCount": "{count} กฎ",
        "universalCetasikas": "สัพพจิตตสาธารณเจตสิก 7",
        "occasionalCetasikas": "ปกิณณกเจตสิก 6",
        "unwholesomeCetasikas": "อกุศลเจตสิก 14",
        "beautifulCetasikas": "โสภณเจตสิก 25",
        "rowCittaSemantics": "แถวจิตที่ {displayIndex}: {name}; ลำดับ {order}; กลุ่ม {group}; เวทนา {feeling}. {action}",
        "cetasikaSemantics": "เจตสิก {name} ({pali}), กลุ่ม {group}. {state} แตะเพื่อดูรายละเอียด",
        "matrixCornerSemantics": "มุมตาราง: แถวคือจิตและคอลัมน์คือเจตสิก",
        "associationSemantics": "{association}: จิต {cittaId} กับ เจตสิก {cetasikaId}",
        "savedItemsCount": "รายการที่บันทึกไว้ {count} รายการ",
        "cittaTab": "จิต",
        "cetasikaTab": "เจตสิก",
        "notesTab": "บันทึก",
        "noBookmarkedCittas": "ยังไม่มีจิตที่คั่นไว้",
        "bookmarkCittaHint": "เปิดบทเรียนและแตะไอคอนคั่นหน้าเพื่อบันทึก",
        "loadingCittas": "กำลังโหลดข้อมูลจิต…",
        "noBookmarkedCetasikas": "ยังไม่มีเจตสิกที่คั่นไว้",
        "loadingCetasikas": "กำลังโหลดข้อมูลเจตสิก…",
        "noNotes": "ยังไม่มีบันทึก",
        "addNoteHint": "แตะไอคอนแก้ไขในบทเรียนเพื่อเพิ่มบันทึกส่วนตัว",
        "deleteNoteQuestion": "ลบบันทึกหรือไม่?",
        "deleteNoteWarning": "บันทึกนี้จะถูกลบอย่างถาวร คุณแน่ใจหรือไม่?",
        "addNote": "เพิ่มบันทึก",
        "removeBookmark": "ลบบุ๊กมาร์ก",
        "editNote": "แก้ไขบันทึก",
        "deleteNote": "ลบบันทึก",
        "noteUpdated": "อัปเดตบันทึกแล้ว",
        "noteSaved": "บันทึกข้อมูลแล้ว",
        "editNoteTitle": "แก้ไขบันทึก",
        "addNoteTitle": "เพิ่มบันทึก",
        "studyNoteHint": "เขียนบันทึกของคุณเกี่ยวกับหัวข้อนี้…\n\nตัวอย่าง: จิตนี้เกิดขึ้นระหว่างการปฏิบัติธรรมเมื่อ…",
        "charactersCount": "{current} / {maximum} ตัวอักษร",
        "update": "อัปเดต",
        "saveNote": "บันทึก",
        "studyProgressPercent": "ความคืบหน้าการศึกษา: {percent}%",
        "modulesCompletedShort": "บทเรียน\nที่สำเร็จ",
        "recommendedNext": "แนะนำบทเรียนถัดไป",
        "progressOverview": "ภาพรวมความคืบหน้า",
        "totalModules": "บทเรียนทั้งหมด",
        "dueForReview": "ถึงกำหนดทบทวน",
        "moduleHasNoData": "บทเรียนนี้ไม่มีข้อมูลจิต/เจตสิก โปรดตรวจสอบข้อมูล JSON",
        "cittasInModule": "จิตในบทเรียนนี้ — {count}",
        "cetasikasInModule": "เจตสิกในบทเรียนนี้ — {count}",
        "reviewCetasikaQuestion": "เจตสิก “{name}” ({pali}) มีความหมายอย่างไร?",
        "groupAnswer": "กลุ่ม: {group}",
        "reviewCittaQuestion": "จิต “{name}” อยู่ในภูมิใดและมีเวทนาอะไร?",
        "cittaReviewAnswer": "ภูมิ: {sphere}\nเวทนา: {feeling}\nบาลี: {pali}",
        "noReviewContent": "บทเรียนนี้ยังไม่มีเนื้อหาทบทวน โปรดกลับมาใหม่ภายหลัง",
        "reviewedCount": "ทบทวนแล้ว {revealed} / {total}",
        "reviewComplete": "คุณทบทวนเนื้อหาครบแล้ว ทำแบบทดสอบเพื่อตรวจความเข้าใจ",
        "tapToReveal": "แตะเพื่อดูคำตอบ",
        "answerLabel": "คำตอบ: {answer}",
        "revealAnswer": "แสดงคำตอบ",
        "moduleQuizTitle": "แบบทดสอบ\n{module}",
        "moduleContentCount": "{count} หัวข้อในบทเรียนนี้",
        "quizMaximumDescription": "คำถามปรนัยสูงสุด 10 ข้อครอบคลุมบทเรียนนี้",
        "startQuiz": "เริ่มแบบทดสอบ",
        "cittasCount": "จิต {count} ดวง",
        "cetasikasCount": "เจตสิก {count} ดวง",
        "noteForItem": "บันทึก: {name}",
        "quizLevelDescription": "แต่ละระดับจะสร้างคำถามสูงสุด {count} ข้อจากบทเรียนนี้",
        "insufficientQuizData": "บทเรียนนี้มีข้อมูลไม่เพียงพอในการสร้างคำถาม",
        "correctAnswers": "ถูกต้อง {score} / {total} ข้อ",
        "quizExcellent": "ยอดเยี่ยม! คุณเข้าใจบทเรียนนี้อย่างเชี่ยวชาญแล้ว",
        "quizTryAgain": "ทบทวนเนื้อหาและลองใหม่อีกครั้ง",
        "quizInsufficientDataMessage": "บทเรียน “{module}” มีข้อมูลไม่เพียงพอในการสร้างคำถาม",
        "quizTypeCetasikaGroup": "การจำแนกเจตสิก",
        "quizTypeFeeling": "การระบุเวทนา",
        "quizTypeConflict": "ความขัดแย้งทางธรรม",
        "quizTypeSphere": "ภูมิ (Sphere)",
        "beginnerDescription": "กลุ่มเจตสิกพื้นฐานและเวทนา",
        "intermediateDescription": "รวมถึงกฎความขัดแย้งของเจตสิก",
        "advancedDescription": "รวมถึงภูมิและคำถามทุกประเภท",
        "trueLabel": "จริง",
        "falseLabel": "เท็จ",
        "trueOrFalse": "จริงหรือเท็จ?",
        "quizCetasikaGroupQuestion": "“{name}” ({pali}) อยู่ในกลุ่มใด?",
        "quizCetasikaGroupExplanation": "“{name}” อยู่ในกลุ่ม {group}\n{description}",
        "quizCetasikaClaim": "“{name}” ({pali}) อยู่ในกลุ่ม {group} จริงหรือเท็จ?",
        "quizCittaFeelingQuestion": "จิต “{name}” มีเวทนาอะไรประกอบร่วม?",
        "quizCittaFeelingExplanation": "“{name}” มี {feeling}",
        "quizCittaFeelingClaim": "จิต “{name}” มี {feeling} จริงหรือเท็จ?",
        "conflictNo": "ไม่ — เป็นปฏิปักษ์กัน",
        "conflictAlwaysYes": "ใช่ — เกิดร่วมกันเสมอ",
        "conflictSometimesYes": "ใช่ — เกิดร่วมกันในบางครั้ง",
        "quizConflictQuestion": "“{first}” และ “{second}” สามารถเกิดร่วมกันในจิตดวงเดียวกันได้หรือไม่?",
        "quizSphereQuestion": "จิต “{name}” จัดอยู่ในภูมิใด?",
        "quizSphereExplanation": "“{name}” อยู่ใน {sphere}",
        "quizSphereClaim": "จิต “{name}” จัดอยู่ใน {sphere} จริงหรือเท็จ?",
        "phaseFoundation": "ระยะที่ 1 — รากฐาน",
        "phaseCausality": "ระยะที่ 2 — เหตุปัจจัย",
        "phaseMastery": "ระยะที่ 3 — ความเชี่ยวชาญ",
        "continueListening": "ฟังต่อ",
        "audioBackgroundLimit": "การเล่นเสียงพื้นหลังขึ้นอยู่กับเครื่องมือแปลงข้อความเป็นเสียงที่ติดตั้งไว้"
    },
    "si": {
        "appName": "අභිධර්මය",
        "appTagline": "අභිධර්ම පිටකය",
        "initializing": "ආරම්භ වෙමින් පවතී…",
        "loadingDoctrineData": "ධර්ම දත්ත පූරණය වෙමින් පවතී…",
        "loadingTakingLonger": "ආරම්භය අපේක්ෂිත කාලයට වඩා වැඩි කාලයක් ගනී...",
        "unknownError": "නොදන්නා දෝෂයක්",
        "dataError": "දත්ත දෝෂයකි",
        "invalidData": "වලංගු නොවන දත්ත",
        "invalidDataDescription": "ධර්ම වලංගුකරණ නීති කඩවීමක් පද්ධතිය විසින් හඳුනාගෙන ඇත.",
        "errorWithMessage": "දෝෂය: {message}",
        "holdGlobeToReset": "පද්ධති භාෂාව නැවත පිහිටුවීමට ලෝක ගෝලය තත්පර 3ක් ඔබාගෙන සිටින්න",
        "restoredSystemLanguage": "පද්ධති භාෂාව නැවත පිහිටුවන ලදී",
        "screenReaderHints": "තිර කියවනය සඳහා ඉඟි",
        "textScale": "පෙළ පරිමාණය",
        "onboardingVisualTitle": "පැහැදිලිව දකින්න",
        "onboardingVisualSubtitle": "සිත් × චෛතසික න්‍යාසය",
        "onboardingVisualBody": "සිත් 121ක් සහ චෛතසික 52ක් අන්තර්ක්‍රියාකාරී න්‍යාසයකින් අධ්‍යයනය කරන්න.",
        "onboardingCausalityTitle": "ගැඹුරින් තේරුම් ගන්න",
        "onboardingCausalitySubtitle": "පටිච්චසමුප්පාදය",
        "onboardingCausalityBody": "පටිච්චසමුප්පාද අංග 12 සහ කර්ම වර්ගීකරණයන් විමසා බලන්න.",
        "onboardingExploreTitle": "ස්වයං අධ්‍යයනය",
        "onboardingExploreSubtitle": "අනුක්‍රමික නොවන අධ්‍යයන මාර්ගය",
        "onboardingExploreBody": "පාඩම් මාලා 10ක් ඔස්සේ ඔබේ දැනුම වර්ධනය කරගන්න.",
        "beginExploring": "ගවේෂණය අරඹන්න",
        "matrixSemantics": "{count}ක් වූ සිත් පෙන්වන අභිධර්ම න්‍යාසය",
        "clearSearch": "සෙවීම හිස් කරන්න",
        "dataWarningsCount": "දත්ත අනතුරු ඇඟවීම් {count}",
        "dataWarningTitle": "දත්ත අනතුරු ඇඟවීම",
        "defilements": "කෙලෙස් (Kilesa)",
        "relatedDhammas": "සම්බන්ධ ධර්ම",
        "kammaTitle": "කර්මය (Kamma)",
        "paliLabel": "පාලි:",
        "stopPronunciation": "උච්චාරණය නවත්වන්න",
        "listenPaliPronunciation": "පාලි උච්චාරණයට සවන් දෙන්න",
        "ttsUnavailable": "මෙම උපාංගයේ කථන සංස්ලේෂණය සඳහා සහය නොදක්වයි.",
        "dragHandleSemantics": "ප්‍රමාණය වෙනස් කිරීමට අදින්න",
        "cittaNumber": "සිත {number}",
        "doctrine": "ධර්ම විග්‍රහය",
        "examples": "උදාහරණ",
        "fixedCetasikasCount": "නියත චෛතසික ({count})",
        "variableCetasikasCount": "අනියත චෛතසික ({count})",
        "personalNote": "පෞද්ගලික සටහන",
        "personalNoteHint": "ඔබේ සටහන ඇතුළත් කරන්න…",
        "wholesome": "කුසල්",
        "functional": "ක්‍රියා",
        "pleasantFeeling": "කායික සුඛ වේදනාව",
        "unpleasantFeeling": "කායික දුක්ඛ වේදනාව",
        "neutralFeeling": "උපේක්ෂා වේදනාව",
        "joyfulFeeling": "සෝමනස්ස වේදනාව",
        "alwaysAssociated": "සැමවිටම යෙදෙන",
        "mayBeAssociated": "සමහරවිට යෙදෙන",
        "fourfoldDefinition": "චතුර්විධ ලක්ෂණ (ලක්ෂණ/රස/පච්චුපට්ඨාන/පදට්ඨාන)",
        "characteristic": "ලක්ෂණය (Lakkhaṇa)",
        "functionLabel": "කෘත්‍යය / රසය (Rasa)",
        "manifestation": "වැටහෙන ආකාරය (Paccupaṭṭhāna)",
        "proximateCause": "ආසන්න හේතුව (Padaṭṭhāna)",
        "doctrinalConflicts": "ධර්ම විරෝධතා",
        "rulesCount": "නීති {count}",
        "universalCetasikas": "සබ්බචිත්තසාධාරණ 7",
        "occasionalCetasikas": "පකිණ්ණක 6",
        "unwholesomeCetasikas": "අකුසල් චෛතසික 14",
        "beautifulCetasikas": "ශෝභන චෛතසික 25",
        "rowCittaSemantics": "සිත් පේළිය {displayIndex}: {name}; අංකය {order}; කාණ්ඩය {group}; වේදනාව {feeling}. {action}",
        "cetasikaSemantics": "චෛතසිකය {name} ({pali}), කාණ්ඩය {group}. {state} විස්තර සඳහා තට්ටු කරන්න.",
        "matrixCornerSemantics": "න්‍යාස කොන: පේළි සිත් වන අතර තීරු චෛතසික වේ",
        "associationSemantics": "{association}: සිත {cittaId} චෛතසිකය {cetasikaId} සමඟ",
        "savedItemsCount": "සුරැකි අයිතම {count}",
        "cittaTab": "සිත්",
        "cetasikaTab": "චෛතසික",
        "notesTab": "සටහන්",
        "noBookmarkedCittas": "සුරැකි සිත් නැත",
        "bookmarkCittaHint": "පාඩමක් විවෘත කර සුරැකීමට බුක්මාක් අයිකනය තට්ටු කරන්න",
        "loadingCittas": "සිත් පූරණය වෙමින් පවතී…",
        "noBookmarkedCetasikas": "සුරැකි චෛතසික නැත",
        "loadingCetasikas": "චෛතසික පූරණය වෙමින් පවතී…",
        "noNotes": "තවම සටහන් නැත",
        "addNoteHint": "පෞද්ගලික සටහනක් එක් කිරීමට සංස්කරණ අයිකනය තට්ටු කරන්න",
        "deleteNoteQuestion": "සටහන මකන්නද?",
        "deleteNoteWarning": "මෙම සටහන ස්ථිරවම මකා දැමෙනු ඇත. ඔබට විශ්වාසද?",
        "addNote": "සටහනක් එක් කරන්න",
        "removeBookmark": "බුක්මාක් ඉවත් කරන්න",
        "editNote": "සටහන සංස්කරණය",
        "deleteNote": "සටහන මකන්න",
        "noteUpdated": "සටහන යාවත්කාලීන කරන ලදී",
        "noteSaved": "සටහන සුරකින ලදී",
        "editNoteTitle": "සටහන සංස්කරණය",
        "addNoteTitle": "සටහනක් එක් කරන්න",
        "studyNoteHint": "මෙම අයිතමය ගැන ඔබේ සටහන ලියන්න…",
        "charactersCount": "අක්ෂර {current} / {maximum}",
        "update": "යාවත්කාලීන කරන්න",
        "saveNote": "සටහන සුරකින්න",
        "studyProgressPercent": "අධ්‍යයන ප්‍රගතිය: {percent}%",
        "modulesCompletedShort": "සම්පූර්ණ කළ\nපාඩම්",
        "recommendedNext": "ඊළඟ නිර්දේශය",
        "progressOverview": "ප්‍රගති සමාලෝචනය",
        "totalModules": "මුළු පාඩම්",
        "dueForReview": "නැවත බැලීමට",
        "moduleHasNoData": "මෙම පාඩමේ දත්ත නැත.",
        "cittasInModule": "මෙම පාඩමේ ඇති සිත් — {count}",
        "cetasikasInModule": "මෙම පාඩමේ ඇති චෛතසික — {count}",
        "reviewCetasikaQuestion": "“{name}” ({pali}) චෛතසිකයේ තේරුම කුමක්ද?",
        "groupAnswer": "කාණ්ඩය: {group}",
        "reviewCittaQuestion": "“{name}” සිත අයත් වන්නේ කුමන භූමියට සහ වේදනාවටද?",
        "cittaReviewAnswer": "භූමිය: {sphere}\nවේදනාව: {feeling}\nපාලි: {pali}",
        "noReviewContent": "මෙම පාඩමේ තවම පුනරීක්ෂණ අන්තර්ගතයක් නොමැත.",
        "reviewedCount": "{revealed} / {total} සමාලෝචනය කර ඇත",
        "reviewComplete": "ඔබ සියලු අන්තර්ගත සමාලෝචනය කර ඇත. ප්‍රශ්නාවලියට මුහුණ දෙන්න.",
        "tapToReveal": "පිළිතුර බැලීමට තට්ටු කරන්න",
        "answerLabel": "පිළිතුර: {answer}",
        "revealAnswer": "පිළිතුර පෙන්වන්න",
        "moduleQuizTitle": "ප්‍රශ්නාවලිය\n{module}",
        "moduleContentCount": "මෙම පාඩමේ අයිතම {count}ක් ඇත",
        "quizMaximumDescription": "මෙම පාඩම ආවරණය වන පරිදි බහුවරණ ප්‍රශ්න 10ක් දක්වා",
        "startQuiz": "ප්‍රශ්නාවලිය අරඹන්න",
        "cittasCount": "සිත් {count}",
        "cetasikasCount": "චෛතසික {count}",
        "noteForItem": "සටහන: {name}",
        "quizLevelDescription": "සෑම මට්ටමක්ම ප්‍රශ්න {count}ක් ජනනය කරයි",
        "insufficientQuizData": "ප්‍රශ්න සෑදීමට ප්‍රමාණවත් දත්ත නොමැත.",
        "correctAnswers": "නිවැරදි {score} / {total}",
        "quizExcellent": "විශිෂ්ටයි! ඔබ මෙම පාඩම ප්‍රගුණ කර ඇත.",
        "quizTryAgain": "කරුණාකර නැවත උත්සාහ කරන්න.",
        "quizInsufficientDataMessage": "“{module}” පාඩම සඳහා දත්ත ප්‍රමාණවත් නොවේ.",
        "quizTypeCetasikaGroup": "චෛතසික වර්ගීකරණය",
        "quizTypeFeeling": "වේදනා හඳුනාගැනීම",
        "quizTypeConflict": "ධර්ම විරෝධතා",
        "quizTypeSphere": "භූමිය",
        "beginnerDescription": "මූලික චෛතසික කාණ්ඩ සහ වේදනා",
        "intermediateDescription": "චෛතසික විරෝධතා ඇතුළත් වේ",
        "advancedDescription": "සියලුම ප්‍රශ්න වර්ග ඇතුළත් වේ",
        "trueLabel": "සත්‍ය",
        "falseLabel": "අසත්‍ය",
        "trueOrFalse": "සත්‍යද අසත්‍යද?",
        "quizCetasikaGroupQuestion": "“{name}” ({pali}) අයත් වන්නේ කුමන කාණ්ඩයටද?",
        "quizCetasikaGroupExplanation": "“{name}” {group}ට අයත් වේ.\n{description}",
        "quizCetasikaClaim": "“{name}” ({pali}) {group}ට අයත් වේ. සත්‍යද අසත්‍යද?",
        "quizCittaFeelingQuestion": "“{name}” සිත සමඟ යෙදෙන වේදනාව කුමක්ද?",
        "quizCittaFeelingExplanation": "“{name}” සිතෙහි {feeling} පවතී.",
        "quizCittaFeelingClaim": "“{name}” සිතෙහි {feeling} පවතී. සත්‍යද අසත්‍යද?",
        "conflictNo": "නැත — ඒවා එකිනෙකට විරුද්ධයි",
        "conflictAlwaysYes": "ඔව් — ඒවා සැමවිටම එකට යෙදේ",
        "conflictSometimesYes": "ඔව් — ඒවා සමහරවිට එකට යෙදේ",
        "quizConflictQuestion": "“{first}” සහ “{second}” එකම සිතක එකට යෙදිය හැකිද?",
        "quizSphereQuestion": "“{name}” සිත අයත් වන්නේ කුමන භූමියටද?",
        "quizSphereExplanation": "“{name}” {sphere}ට අයත් වේ.",
        "quizSphereClaim": "“{name}” සිත {sphere}ට අයත් වේ. සත්‍යද අසත්‍යද?",
        "phaseFoundation": "අදියර 1 — පදනම",
        "phaseCausality": "අදියර 2 — හේතුඵල",
        "phaseMastery": "අදියර 3 — ප්‍රවීණත්වය",
        "continueListening": "දිගටම සවන් දෙන්න",
        "audioBackgroundLimit": "පසුබිම් ශ්‍රව්‍ය ධාවනය ස්ථාපිත හඬ එන්ජිම මත රඳා පවතී"
    },
    "my": {
        "appName": "အဘိဓမ္မာ",
        "appTagline": "အဘိဓမ္မာပိဋကတ်",
        "initializing": "စတင်နေသည်…",
        "loadingDoctrineData": "တရားတော်အချက်အလက်များ တင်နေသည်…",
        "loadingTakingLonger": "စတင်ခြင်းသည် မျှော်လင့်ထားသည်ထက် ပိုကြာနေပါသည်...",
        "unknownError": "အမည်မသိ အမှား",
        "dataError": "ဒေတာ အမှား",
        "invalidData": "မမှန်ကန်သော ဒေတာ",
        "invalidDataDescription": "ဓမ္မ စစ်ဆေးမှု စည်းမျဉ်းများ ချိုးဖောက်မှုကို စနစ်က တွေ့ရှိထားသည်။",
        "errorWithMessage": "အမှား: {message}",
        "holdGlobeToReset": "စနစ်သုံးဘာသာစကားသို့ ပြန်ထားရန် ကမ္ဘာလုံးပုံကို ၃ စက္ကန့် ဖိထားပါ",
        "restoredSystemLanguage": "စနစ်သုံးဘာသာစကားသို့ ပြန်ထားပြီးပါပြီ",
        "screenReaderHints": "စခရင်ဖတ်စနစ် အထောက်အကူများ",
        "textScale": "စာလုံးအရွယ်အစား",
        "onboardingVisualTitle": "ရှင်းလင်းစွာ မြင်ပါ",
        "onboardingVisualSubtitle": "စိတ် × စေတသိက် ဇယား",
        "onboardingVisualBody": "စိတ် ၁၂၁ ပါးနှင့် စေတသိက် ၅၂ ပါးတို့၏ ယှဉ်တွဲပုံကို အပြန်အလှန်လေ့လာပါ။",
        "onboardingCausalityTitle": "နက်နဲစွာ နားလည်ပါ",
        "onboardingCausalitySubtitle": "ပဋိစ္စသမုပ္ပါဒ်",
        "onboardingCausalityBody": "ပဋိစ္စသမုပ္ပါဒ် အင်္ဂါ ၁၂ ပါးနှင့် ကံအမျိုးအစားများကို လေ့လာပါ။",
        "onboardingExploreTitle": "မိမိဘာသာ ရှာဖွေလေ့လာပါ",
        "onboardingExploreSubtitle": "လွတ်လပ်သော သင်ယူမှုလမ်းကြောင်း",
        "onboardingExploreBody": "သင်ခန်းစာ ၁၀ ခုမှတစ်ဆင့် မိမိစိတ်ကြိုက် လေ့လာသင်ယူနိုင်ပါသည်။",
        "beginExploring": "စတင်လေ့လာပါ",
        "matrixSemantics": "စိတ် {count} ပါး ပြသထားသော အဘိဓမ္မာ ဇယား",
        "clearSearch": "ရှာဖွေမှု ရှင်းပါ",
        "dataWarningsCount": "ဒေတာသတိပေးချက် {count} ခု",
        "dataWarningTitle": "ဒေတာ သတိပေးချက်",
        "defilements": "ကိလေသာ (Kilesa)",
        "relatedDhammas": "ဆက်စပ်တရားများ",
        "kammaTitle": "ကံ (Kamma)",
        "paliLabel": "ပါဠိ:",
        "stopPronunciation": "အသံထွက် ရပ်ပါ",
        "listenPaliPronunciation": "ပါဠိ အသံထွက် နားထောင်ပါ",
        "ttsUnavailable": "ဤစက်ပစ္စည်းတွင် အသံထွက်စနစ် မရနိုင်ပါ။",
        "dragHandleSemantics": "အရွယ်အစားညှိရန် ဆွဲပါ",
        "cittaNumber": "စိတ် {number}",
        "doctrine": "ဓမ္မ ရှင်းလင်းချက်",
        "examples": "ဥပမာများ",
        "fixedCetasikasCount": "နိယတစေတသိက် ({count})",
        "variableCetasikasCount": "အနိယတစေတသိက် ({count})",
        "personalNote": "ကိုယ်ပိုင်မှတ်စု",
        "personalNoteHint": "မှတ်စုရေးပါ…",
        "wholesome": "ကုသိုလ်",
        "functional": "ကြိယာ",
        "pleasantFeeling": "ကာယိက သုခဝေဒနာ",
        "unpleasantFeeling": "ကာယိက ဒုက္ခဝေဒနာ",
        "neutralFeeling": "ဥပေက္ခာဝေဒနာ",
        "joyfulFeeling": "သောမနဿဝေဒနာ",
        "alwaysAssociated": "အမြဲယှဉ်တွဲသော",
        "mayBeAssociated": "တစ်ခါတစ်ရံယှဉ်တွဲသော",
        "fourfoldDefinition": "လက္ခဏာဒိစတုက္က (လက္ခဏာ/ရသ/ပစ္စုပဋ္ဌာန်/ပဒဋ္ဌာန်)",
        "characteristic": "လက္ခဏာ (Lakkhaṇa)",
        "functionLabel": "ကိစ္စ / ရသ (Rasa)",
        "manifestation": "ပစ္စုပဋ္ဌာန် (Paccupaṭṭhāna)",
        "proximateCause": "ပဒဋ္ဌာန် (Padaṭṭhāna)",
        "doctrinalConflicts": "ဓမ္မဆန့်ကျင်မှု စည်းမျဉ်းများ",
        "rulesCount": "စည်းမျဉ်း {count} ခု",
        "universalCetasikas": "သဗ္ဗစိတ္တသာဓာရဏ ၇",
        "occasionalCetasikas": "ပကိဏ်း ၆",
        "unwholesomeCetasikas": "အကုသိုလ်စေတသိက် ၁၄",
        "beautifulCetasikas": "သောဘဏစေတသိက် ၂၅",
        "rowCittaSemantics": "စိတ်အစဉ် {displayIndex}: {name}; မူရင်းအမှတ် {order}; အုပ်စု {group}; ဝေဒနာ {feeling}. {action}",
        "cetasikaSemantics": "စေတသိက် {name} ({pali}), အုပ်စု {group}. {state} အသေးစိတ်ကြည့်ရန် နှိပ်ပါ။",
        "matrixCornerSemantics": "ဇယားထောင့်: အလျားလိုက်သည် စိတ်ဖြစ်ပြီး ဒေါင်လိုက်သည် စေတသိက်ဖြစ်သည်",
        "associationSemantics": "{association}: စိတ် {cittaId} နှင့် စေတသိက် {cetasikaId}",
        "savedItemsCount": "သိမ်းဆည်းထားသော အရာ {count} ခု",
        "cittaTab": "စိတ်",
        "cetasikaTab": "စေတသိက်",
        "notesTab": "မှတ်စုများ",
        "noBookmarkedCittas": "မှတ်သားထားသော စိတ်မရှိပါ",
        "bookmarkCittaHint": "သိမ်းဆည်းရန် သင်ခန်းစာကိုဖွင့်ပြီး အမှတ်အသား အိုင်ကွန်ကို နှိပ်ပါ",
        "loadingCittas": "စိတ်အချက်အလက်များ တင်နေသည်…",
        "noBookmarkedCetasikas": "မှတ်သားထားသော စေတသိက်မရှိပါ",
        "loadingCetasikas": "စေတသိက်အချက်အလက်များ တင်နေသည်…",
        "noNotes": "မှတ်စု မရှိသေးပါ",
        "addNoteHint": "ကိုယ်ပိုင်မှတ်စု ရေးရန် ပြင်ဆင်ရန် အိုင်ကွန်ကို နှိပ်ပါ",
        "deleteNoteQuestion": "မှတ်စုကို ဖျက်မလား?",
        "deleteNoteWarning": "ဤမှတ်စုကို အပြီးအပိုင် ဖျက်ပါမည်။ သေချာပါသလား?",
        "addNote": "မှတ်စု ထည့်ပါ",
        "removeBookmark": "အမှတ်အသား ဖယ်ရှားပါ",
        "editNote": "မှတ်စု ပြင်ပါ",
        "deleteNote": "မှတ်စု ဖျက်ပါ",
        "noteUpdated": "မှတ်စု အသစ်ပြင်ပြီးပါပြီ",
        "noteSaved": "မှတ်စု သိမ်းဆည်းပြီးပါပြီ",
        "editNoteTitle": "မှတ်စု ပြင်ဆင်ရန်",
        "addNoteTitle": "မှတ်စု အသစ်ထည့်ရန်",
        "studyNoteHint": "ဤအကြောင်းအရာနှင့် ပတ်သက်၍ ကိုယ်ပိုင်မှတ်စု ရေးပါ…",
        "charactersCount": "စာလုံးရေ {current} / {maximum}",
        "update": "ပြင်ဆင်ပါ",
        "saveNote": "မှတ်စု သိမ်းပါ",
        "studyProgressPercent": "သင်ယူမှု တိုးတက်မှု: {percent}%",
        "modulesCompletedShort": "ပြီးစီးသော\nသင်ခန်းစာများ",
        "recommendedNext": "ဆက်လက်လေ့လာရန်",
        "progressOverview": "တိုးတက်မှု ခြုံငုံသုံးသပ်ချက်",
        "totalModules": "စုစုပေါင်း သင်ခန်းစာများ",
        "dueForReview": "ပြန်လည်လေ့ကျက်ရန်",
        "moduleHasNoData": "ဤသင်ခန်းစာတွင် အချက်အလက် မရှိသေးပါ။",
        "cittasInModule": "ဤသင်ခန်းစာပါ စိတ်များ — {count}",
        "cetasikasInModule": "ဤသင်ခန်းစာပါ စေတသိက်များ — {count}",
        "reviewCetasikaQuestion": "စေတသိက် “{name}” ({pali}) ၏ အဓိပ္ပာယ်မှာ အဘယ်နည်း?",
        "groupAnswer": "အုပ်စု: {group}",
        "reviewCittaQuestion": "စိတ် “{name}” သည် မည်သည့်ဘုံနှင့် မည်သည့်ဝေဒနာ ရှိသနည်း?",
        "cittaReviewAnswer": "ဘုံ: {sphere}\nဝေဒနာ: {feeling}\nပါဠိ: {pali}",
        "noReviewContent": "ဤသင်ခန်းစာတွင် ပြန်လည်လေ့ကျက်ရန် အကြောင်းအရာ မရှိသေးပါ။",
        "reviewedCount": "လေ့ကျက်ပြီး {revealed} / {total}",
        "reviewComplete": "သင်ခန်းစာအားလုံး လေ့ကျက်ပြီးပါပြီ။ စမ်းသပ်စစ်ဆေးမှု ဖြေဆိုပါ။",
        "tapToReveal": "အဖြေကြည့်ရန် နှိပ်ပါ",
        "answerLabel": "အဖြေ: {answer}",
        "revealAnswer": "အဖြေ ပြပါ",
        "moduleQuizTitle": "မေးခွန်းများ\n{module}",
        "moduleContentCount": "ဤသင်ခန်းစာတွင် အကြောင်းအရာ {count} ခု ပါဝင်ပါသည်",
        "quizMaximumDescription": "ဤသင်ခန်းစာကို လွှမ်းခြုံသော ရွေးချယ်စရာ မေးခွန်း ၁၀ ခုအထိ",
        "startQuiz": "စစ်ဆေးမှု စတင်ပါ",
        "cittasCount": "စိတ် {count} ပါး",
        "cetasikasCount": "စေတသိက် {count} ပါး",
        "noteForItem": "မှတ်စု: {name}",
        "quizLevelDescription": "အဆင့်တစ်ခုစီသည် မေးခွန်း {count} ခု ထုတ်ပေးပါသည်",
        "insufficientQuizData": "မေးခွန်းထုတ်ရန် ဒေတာ မလုံလောက်ပါ။",
        "correctAnswers": "မှန်ကန်မှု {score} / {total}",
        "quizExcellent": "ထူးချွန်ပါသည်! သင် ဤသင်ခန်းစာကို ကျွမ်းကျင်စွာ တတ်မြောက်သွားပါပြီ။",
        "quizTryAgain": "ပြန်လည်လေ့လာပြီး ထပ်မံကြိုးစားပါ။",
        "quizInsufficientDataMessage": "“{module}” အတွက် မေးခွန်းထုတ်ရန် ဒေတာ မလုံလောက်ပါ။",
        "quizTypeCetasikaGroup": "စေတသိက် ခွဲခြားခြင်း",
        "quizTypeFeeling": "ဝေဒနာ ခွဲခြားခြင်း",
        "quizTypeConflict": "ဓမ္မ ဆန့်ကျင်မှုများ",
        "quizTypeSphere": "ဘုံ အဆင့်အတန်း",
        "beginnerDescription": "အခြေခံ စေတသိက် အုပ်စုများနှင့် ဝေဒနာများ",
        "intermediateDescription": "စေတသိက် ဆန့်ကျင်မှု စည်းမျဉ်းများ ပါဝင်သည်",
        "advancedDescription": "ဘုံများနှင့် မေးခွန်းပုံစံ အားလုံး ပါဝင်သည်",
        "trueLabel": "မှန်",
        "falseLabel": "မှား",
        "trueOrFalse": "မှန် သို့မဟုတ် မှား?",
        "quizCetasikaGroupQuestion": "“{name}” ({pali}) သည် မည်သည့်အုပ်စုတွင် ပါဝင်သနည်း?",
        "quizCetasikaGroupExplanation": "“{name}” သည် {group} တွင် ပါဝင်သည်။\n{description}",
        "quizCetasikaClaim": "“{name}” ({pali}) သည် {group} တွင် ပါဝင်သည်။ မှန် သို့မဟုတ် မှား?",
        "quizCittaFeelingQuestion": "စိတ် “{name}” တွင် မည်သည့်ဝေဒနာ ယှဉ်သနည်း?",
        "quizCittaFeelingExplanation": "“{name}” တွင် {feeling} ယှဉ်သည်။",
        "quizCittaFeelingClaim": "စိတ် “{name}” တွင် {feeling} ယှဉ်သည်။ မှန် သို့မဟုတ် မှား?",
        "conflictNo": "မဟုတ် — ဆန့်ကျင်ဘက်ဖြစ်သည်",
        "conflictAlwaysYes": "ဟုတ် — အမြဲ အတူယှဉ်တွဲဖြစ်သည်",
        "conflictSometimesYes": "ဟုတ် — တစ်ခါတစ်ရံ အတူယှဉ်တွဲဖြစ်သည်",
        "quizConflictQuestion": "“{first}” နှင့် “{second}” တို့ စိတ်တစ်ခုတည်းတွင် အတူတကွ ဖြစ်နိုင်သလား?",
        "quizSphereQuestion": "စိတ် “{name}” သည် မည်သည့်ဘုံသို့ သက်ရောက်သနည်း?",
        "quizSphereExplanation": "“{name}” သည် {sphere} ဘုံသို့ သက်ရောက်သည်။",
        "quizSphereClaim": "စိတ် “{name}” သည် {sphere} ဘုံသို့ သက်ရောက်သည်။ မှန် သို့မဟုတ် မှား?",
        "phaseFoundation": "အဆင့် ၁ — အခြေခံ",
        "phaseCausality": "အဆင့် ၂ — အကြောင်းအကျိုး",
        "phaseMastery": "အဆင့် ၃ — ကျွမ်းကျင်မှု",
        "continueListening": "ဆက်လက် နားထောင်ပါ",
        "audioBackgroundLimit": "နောက်ခံအသံဖွင့်ခြင်းသည် ထည့်သွင်းထားသော အသံအင်ဂျင်ပေါ်တွင် မူတည်ပါသည်"
    }
}

# Update all ARB files
files = sorted(L10N.glob("app_*.arb"))
for f in files:
    data = json.load(open(f, encoding="utf-8"))
    locale = data.get("@@locale", f.stem.replace("app_", ""))
    updated = False
    
    # 1. Add audio/karaoke keys if missing
    if locale in AUDIO_KARAOKE_TRANSLATIONS:
        for k, v in AUDIO_KARAOKE_TRANSLATIONS[locale].items():
            if k not in data or data[k] == en_template.get(k):
                data[k] = v
                updated = True
                
    # 2. Add priority translations
    if locale in PRIORITY_TRANSLATIONS:
        for k, v in PRIORITY_TRANSLATIONS[locale].items():
            data[k] = v
            updated = True
            
    # 3. Ensure all keys from template exist
    for k in en_template:
        if k not in data:
            if k.startswith("@"):
                data[k] = en_template[k]
            else:
                data[k] = en_template[k]
            updated = True
            
    # Ensure all @key metadata exists
    for k in en_template:
        if k.startswith("@") and k not in data:
            data[k] = en_template[k]
            updated = True

    with open(f, "w", encoding="utf-8") as fp:
        json.dump(data, fp, ensure_ascii=False, indent=2)
        fp.write("\n")
    print(f"Updated {f.name}")

print("All ARBs updated successfully")
