#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate docs/study-content-sources.md from assets/content/content_vi.json.

Derived from the built content so the audit trail can never drift from what
actually ships. Run after tool/content/build_content.py.
"""

from __future__ import annotations

import json
import os
from collections import defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
VI = os.path.join(ROOT, "assets", "content", "content_vi.json")
OUT = os.path.join(ROOT, "docs", "study-content-sources.md")

HEADER = """# Study content — source notes

Auto-generated by `tool/content/build_source_notes.py`. **Do not edit by hand.**

Every lesson section, review card and quiz seed shipped in
`assets/content/content_vi.json` carries `sourceRefs` pointing at a file and
page in `reference/`. This document is the flattened audit trail.

* Vietnamese is the source of truth; page numbers are 1-based PDF pages as
  reported by `tool/extract_pdf_text.py`.
* Anything the PDFs do not support is marked `source_missing` rather than
  inferred — see the "Known gaps" section at the end.

"""

GAPS = """
## Known gaps

| Module | Gap | Handling |
| --- | --- | --- |
| M6_NGHIEP | `assets/data/kammas.json` ships 12 kammas, but `VDP-Nghiep.pdf` teaches the full Kammacatukka of 16 (4 groups of 4). The 4th group, *Lãnh vực trổ quả*, has no dataset entities. | Taught in lesson section `M6_S06` instead of being forced into the dataset. The dataset is left unchanged. |
| M10_LO_TRINH | `assets/data/vithis.json` contains `VT_VITHIMUTTA`, but `VDP-LoTrinhTam.pdf` has **no** dedicated Vīthimutta (ngoại lộ) section. A grep for `vīthimutta` / `ngoại lộ` across all 11 extracted PDFs returned no relevant hit. | Section `M10_S09` documents this explicitly as `source_missing` with a TODO. Candidate follow-up source: `VDP-NguoiVaCoi.pdf`. |
| All modules (English) | Lesson prose is **not translated to English**. | `content_en.json` marks each module `translationStatus: "source_only"`, `needsReview: true`. The runtime `en -> vi` fallback chain serves the Vietnamese source, so no module is ever empty. |

## PDFs not used for lesson content

`VDP-6PhapRieng.pdf`, `VDP-NguoiVaCoi.pdf`, `VDP-SoDoSieuLyHocCoBan.pdf` and
`VDP-TamSoPhoiHop.pdf` were extracted and searched but no passage from them is
cited by the current content. They remain available for the gaps above.
"""


def main() -> None:
    data = json.load(open(VI, encoding="utf-8"))
    modules = data["studyModules"]

    lines = [HEADER]

    # Per-PDF summary first.
    per_file: dict[str, set] = defaultdict(set)
    for mid, module in modules.items():
        for key in ("lessonSections", "reviewCards", "quizSeeds"):
            for item in module[key]:
                for ref in item.get("sourceRefs", []):
                    per_file[ref["file"]].add((mid, ref["page"]))

    lines.append("## PDFs cited, by file\n")
    lines.append("| PDF | Pages cited | Modules |")
    lines.append("| --- | --- | --- |")
    for file in sorted(per_file):
        pages = sorted({p for _m, p in per_file[file]})
        mods = sorted({m for m, _p in per_file[file]})
        lines.append(
            f"| `{file}` | {', '.join(str(p) for p in pages)} | {', '.join(mods)} |"
        )
    lines.append("")

    lines.append("## Per-module detail\n")
    for mid, module in modules.items():
        counts = (
            f"{len(module['lessonSections'])} lesson sections · "
            f"{len(module['reviewCards'])} review cards · "
            f"{len(module['quizSeeds'])} quiz seeds"
        )
        lines.append(f"### {mid} — {module['title']}\n")
        lines.append(f"{module['description']}\n")
        lines.append(f"*{counts}*\n")
        lines.append("| Section | Title | Sources |")
        lines.append("| --- | --- | --- |")
        for section in module["lessonSections"]:
            refs = "; ".join(
                f"`{r['file']}` p.{r['page']}"
                + (f" — {r['note']}" if r.get("note") else "")
                for r in section.get("sourceRefs", [])
            ) or "**source_missing**"
            lines.append(f"| `{section['id']}` | {section['title']} | {refs} |")
        lines.append("")

    lines.append(GAPS)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
