# -*- coding: utf-8 -*-
"""Authored lesson content for M6_NGHIEP and M8_NHAN_DUYEN (Vietnamese source)."""

NGHIEP = "VDP-Nghiep.pdf"
SODO = "VDP-SoDoNghiep.pdf"
DUYEN = "VDP-ToatYeuVeDuyen.pdf"


def ref(file, page, note=None):
    d = {"file": file, "page": page}
    if note:
        d["note"] = note
    return d


M6_VI = {
    "title": "Nghiệp (Kamma)",
    "description": "Định nghĩa Nghiệp, bốn nhóm phân loại (16 loại) và liên hệ giữa Nghiệp với Tâm.",
    "translationStatus": "reviewed",
    "lessonSections": [
        {
            "id": "M6_S01",
            "title": "Nghiệp là gì?",
            "summary": "Nghiệp là hành động có chủ ý; pháp bản thể là tâm sở Tư (Cetanā).",
            "body": [
                "Kamma – Nghiệp nghĩa là hành động, là ý tạo tác. Pháp bản thể của Nghiệp chính là tâm sở Tư (Cetanā): sự cố ý tạo tác.",
                "Đức Phật dạy: “Cetanāhaṃ, bhikkhave, kammaṃ vadāmi” – “Này các Tỳ khưu, Như Lai dạy: Cố ý là Nghiệp.”",
                "Nghiệp sanh khởi qua ba môn: Thân, Khẩu và Ý. Trong đó Ý nghiệp được xem là tối trọng, vì thân và khẩu đều do tâm điều động.",
                "Sáu nhân làm tập khởi cho Nghiệp là: Tham, Sân, Si (bất thiện) và Vô tham, Vô sân, Vô si (thiện). Tài liệu dẫn: “Lobho nidānaṃ kammānaṃ samudayāya” – Tham là tập khởi khiến các Nghiệp sanh lên.",
            ],
            "keyTerms": [
                {"id": "TERM_KAMMA", "term": "Nghiệp", "pali": "Kamma", "meaning": "Hành động có chủ ý, ý tạo tác"},
                {"id": "TERM_CETANA", "term": "Tư", "pali": "Cetanā", "meaning": "Tâm sở cố ý — pháp bản thể của Nghiệp"},
                {"id": "TERM_KAYAKAMMA", "term": "Thân nghiệp", "pali": "Kāyakamma", "meaning": "Nghiệp tạo qua thân môn"},
                {"id": "TERM_VACIKAMMA", "term": "Khẩu nghiệp", "pali": "Vacīkamma", "meaning": "Nghiệp tạo qua khẩu môn"},
                {"id": "TERM_MANOKAMMA", "term": "Ý nghiệp", "pali": "Manokamma", "meaning": "Nghiệp tạo qua ý môn — tối trọng"},
            ],
            "sourceRefs": [ref(SODO, 2, "KAMMA – NGHIỆP: định nghĩa, Cetanā, 6 nhân, Ý nghiệp tối trọng")],
        },
        {
            "id": "M6_S02",
            "title": "Bốn nhóm Nghiệp — Kammacatukka",
            "summary": "16 loại Nghiệp chia thành 4 nhóm: phận sự, năng lực, thời gian trổ quả, lãnh vực trổ quả.",
            "body": [
                "Kammacatukka phân Nghiệp thành 4 nhóm, mỗi nhóm 4 loại, tổng cộng 16 loại.",
                "Nhóm 1 — Phận sự của Nghiệp (kiccavasena): Sanh nghiệp, Trì nghiệp, Chướng nghiệp, Đoạn nghiệp.",
                "Nhóm 2 — Năng lực / thứ tự trổ quả (pākadānapariyāyena): Trọng nghiệp, Cận tử nghiệp, Thường nghiệp, Khinh thiểu nghiệp.",
                "Nhóm 3 — Thời gian trổ quả (pākakālavasena): Hiện báo nghiệp, Sanh báo nghiệp, Hậu báo nghiệp, Vô hiệu nghiệp.",
                "Nhóm 4 — Nơi chốn / lãnh vực trổ quả (pākaṭṭhānavasena): Nghiệp Bất thiện, Nghiệp Thiện Dục giới, Nghiệp Thiện Sắc giới, Nghiệp Thiện Vô sắc giới.",
            ],
            "keyTerms": [
                {"id": "TERM_KAMMACATUKKA", "term": "Bốn nhóm Nghiệp", "pali": "Kammacatukka", "meaning": "16 loại Nghiệp chia thành 4 nhóm"},
            ],
            "sourceRefs": [
                ref(SODO, 1, "SƠ ĐỒ NGHIỆP: 16 loại phân thành 4 nhóm"),
                ref(NGHIEP, 2, "Kammacatuka — bốn cách phân loại kèm Pāli"),
            ],
        },
        {
            "id": "M6_S03",
            "title": "Nhóm 1 — Phận sự của Nghiệp",
            "summary": "Sanh, Trì, Chướng, Đoạn: bốn chức năng của Nghiệp đối với đời sống.",
            "body": [
                "Sanh nghiệp (Janakakamma): nghiệp tạo nên Danh uẩn và Sắc uẩn trong thời tục sinh, làm cho tâm quả dị thục sanh lên, tức Thức tục sinh (Paṭisandhi viññāṇa).",
                "Trì nghiệp (Upatthambhakakamma): nghiệp trợ giúp, nuôi dưỡng, nâng đỡ cho Sanh nghiệp và làm các uẩn tiếp nối. Trì nghiệp cùng loại (thiện hoặc bất thiện) với Sanh nghiệp và tồn tại cho đến khi Tử tâm xuất hiện.",
                "Chướng nghiệp (Upapīḷakakamma): nghiệp ngăn cản, làm giảm suy năng lực và làm chậm trễ sự trổ quả của Sanh nghiệp. Chướng nghiệp luôn ngược loại với Sanh nghiệp. Tài liệu ghi rõ: Chướng nghiệp không có trong cõi Sắc và cõi Vô sắc.",
                "Đoạn nghiệp (Upaghātakakamma): nghiệp cắt đứt các nghiệp khác hoặc cắt đứt quả của nghiệp khác. Đoạn nghiệp mạnh hơn Chướng nghiệp — Chướng nghiệp chỉ cản trở, còn Đoạn nghiệp diệt trừ Sanh nghiệp.",
            ],
            "keyTerms": [
                {"id": "TERM_JANAKA", "term": "Sanh nghiệp", "pali": "Janakakamma", "meaning": "Nghiệp tái tạo, cho quả tục sinh"},
                {"id": "TERM_UPATTHAMBHAKA", "term": "Trì nghiệp", "pali": "Upatthambhakakamma", "meaning": "Nghiệp trợ duyên, nuôi dưỡng"},
                {"id": "TERM_UPAPILAKA", "term": "Chướng nghiệp", "pali": "Upapīḷakakamma", "meaning": "Nghiệp ngăn cản, làm suy giảm"},
                {"id": "TERM_UPAGHATAKA", "term": "Đoạn nghiệp", "pali": "Upaghātakakamma", "meaning": "Nghiệp cắt đứt, tiêu diệt nghiệp khác"},
                {"id": "TERM_PATISANDHI", "term": "Thức tục sinh", "pali": "Paṭisandhi viññāṇa", "meaning": "Tâm nối liền kiếp sống mới"},
            ],
            "sourceRefs": [
                ref(SODO, 2, "Sanh nghiệp — Janakakamma"),
                ref(SODO, 4, "Trì nghiệp — Upatthambhakakamma"),
                ref(SODO, 5, "Chướng nghiệp và Đoạn nghiệp"),
            ],
        },
        {
            "id": "M6_S04",
            "title": "Nhóm 2 — Năng lực / thứ tự trổ quả",
            "summary": "Trọng nghiệp trổ trước, rồi Cận tử, Thường nghiệp, sau cùng là Khinh thiểu nghiệp.",
            "body": [
                "Trọng nghiệp (Garukakamma): nghiệp nghiêm trọng, cho quả chắc chắn, không nghiệp nào ngăn chặn được. Về bất thiện gồm Ngũ nghịch đại tội (giết mẹ, giết cha, giết A-la-hán, chia rẽ Tăng, làm chảy máu thân Phật) và Tà kiến nhất định. Về thiện là 9 tâm Thiện Đáo đại (thiền Sắc giới và Vô sắc giới).",
                "Theo tài liệu, sức mạnh của ác trọng nghiệp xếp thứ tự: mạnh nhất là Tà kiến nhất định, kế đến chia rẽ Tăng, làm chảy máu thân Phật, rồi giết cha và giết mẹ tùy theo giới đức.",
                "Cận tử nghiệp (Āsannakamma): nghiệp thiện hay bất thiện khởi sanh lúc kề cận cái chết, là lộ tâm diễn hoạt cuối cùng của kiếp sống và làm điều kiện cho kiếp sống mới. Có trường hợp nghịch: người thường hành thiện mà lúc cận tử nhớ điều ác thì sanh cảnh khổ, và ngược lại — nhưng các nghiệp đã tạo không vì vậy mà mất đi.",
                "Thường nghiệp (Āciṇṇakamma): hành động thiện hay bất thiện làm thường xuyên thành thói quen, tạo nên khuynh hướng sống của người đó. Khi lâm chung nhớ lại các việc thường làm thì nghiệp này rơi vào Cận tử nghiệp, nếu không có Trọng nghiệp.",
                "Khinh thiểu nghiệp / Tích lũy nghiệp (Kaṭattākamma): các hành động ngoài ba loại trên, nghiệp nhẹ, thường không cho quả; chỉ cho quả khi không có Trọng nghiệp hay Thường nghiệp trổ.",
            ],
            "keyTerms": [
                {"id": "TERM_GARUKA", "term": "Trọng nghiệp", "pali": "Garukakamma", "meaning": "Nghiệp nặng, cho quả chắc chắn"},
                {"id": "TERM_ANANTARIYA", "term": "Vô gián nghiệp", "pali": "Ānantariyakamma", "meaning": "Ngũ nghịch đại tội"},
                {"id": "TERM_ASANNA", "term": "Cận tử nghiệp", "pali": "Āsannakamma", "meaning": "Nghiệp lúc lâm chung"},
                {"id": "TERM_ACINNA", "term": "Thường nghiệp", "pali": "Āciṇṇakamma", "meaning": "Nghiệp thói quen, tập quán"},
                {"id": "TERM_KATATTA", "term": "Khinh thiểu nghiệp", "pali": "Kaṭattākamma", "meaning": "Nghiệp nhẹ, tích lũy"},
            ],
            "sourceRefs": [
                ref(SODO, 6, "Trọng nghiệp — Garukakamma, Ngũ nghịch đại tội"),
                ref(SODO, 7, "Tà kiến nhất định, Trọng nghiệp thiện"),
                ref(SODO, 8, "Cận tử nghiệp và Thường nghiệp"),
                ref(SODO, 9, "Khinh thiểu nghiệp — Kaṭattākamma"),
            ],
        },
        {
            "id": "M6_S05",
            "title": "Nhóm 3 — Nghiệp thời (thời gian trổ quả)",
            "summary": "Bốn loại theo thời gian, căn cứ trên 7 sát-na Đổng lực (Javana).",
            "body": [
                "Nghiệp thời (Pākakālakamma) được xác định căn cứ nơi lộ tâm Đổng lực — 7 sát-na Javana.",
                "Sát-na Đổng lực thứ 1 là yếu nhất (sanh đầu tiên, không có sát-na đồng loại hỗ trợ) → chỉ cho quả ngay trong kiếp hiện tại: Hiện báo nghiệp (Diṭṭhadhammavedanīyakamma). Nếu không trổ trong kiếp này thì trở thành Vô hiệu nghiệp.",
                "Sát-na Đổng lực thứ 7 yếu thứ nhì (cận kề sự diệt) → cho quả trong kiếp kế: Sanh báo nghiệp (Upapajjavedanīyakamma). Hết kiếp thứ 2 mà chưa cho quả thì thành Vô hiệu nghiệp.",
                "Năm sát-na thứ 2 đến thứ 6 → cho quả bất định về thời điểm, kể từ kiếp thứ 3 cho đến khi Niết-bàn: Hậu báo nghiệp (Aparāpariyavedanīyakamma). Riêng sát-na thứ 4 mạnh nhất vì ở giai đoạn cực thịnh.",
                "Vô hiệu nghiệp (Ahosikamma): nghiệp đã tạo mà không cho quả. Tài liệu nhấn mạnh: Hậu báo nghiệp thường không tiêu hoại nếu chưa được cho quả — “Aparāparavedanīyaṃ pana vipākaṃ adatvā na nassati”.",
            ],
            "keyTerms": [
                {"id": "TERM_JAVANA", "term": "Đổng lực", "pali": "Javana", "meaning": "7 sát-na xử lý cảnh, nơi lưu giữ hạt giống nghiệp"},
                {"id": "TERM_DITTHADHAMMA", "term": "Hiện báo nghiệp", "pali": "Diṭṭhadhammavedanīyakamma", "meaning": "Cho quả ngay kiếp hiện tại"},
                {"id": "TERM_UPAPAJJA", "term": "Sanh báo nghiệp", "pali": "Upapajjavedanīyakamma", "meaning": "Cho quả kiếp kế"},
                {"id": "TERM_APARAPARIYA", "term": "Hậu báo nghiệp", "pali": "Aparāpariyavedanīyakamma", "meaning": "Cho quả từ kiếp thứ 3 trở đi"},
                {"id": "TERM_AHOSI", "term": "Vô hiệu nghiệp", "pali": "Ahosikamma", "meaning": "Nghiệp không còn cơ hội cho quả"},
            ],
            "sourceRefs": [
                ref(SODO, 10, "Nghiệp thời — Pākakālakamma, 7 sát na Javana, Hiện báo nghiệp"),
                ref(SODO, 11, "Sanh báo nghiệp — Upapajjavedanīyakamma"),
                ref(SODO, 12, "Hậu báo nghiệp — Aparāpariyavedanīyakamma"),
                ref(SODO, 13, "Vô hiệu nghiệp — Ahosikamma"),
            ],
        },
        {
            "id": "M6_S06",
            "title": "Nhóm 4 — Lãnh vực trổ quả",
            "summary": "Nghiệp Bất thiện, Thiện Dục giới, Thiện Sắc giới, Thiện Vô sắc giới.",
            "body": [
                "Nghiệp Bất thiện thuộc Dục giới: chi pháp là 12 tâm Bất thiện phối hợp với tâm sở Tư. Ngoại trừ Phóng dật, nghiệp bất thiện đưa đến tái sanh trong Khổ cảnh; nhưng trong kiếp sống thì cả 12 đều có trổ quả.",
                "Nghiệp Thiện thuộc Dục giới: chi pháp là 8 tâm Thiện Dục giới Tịnh hảo phối hợp với tâm sở Tư, đưa đến tái sanh trong cõi vui Dục giới.",
                "Nghiệp Thiện thuộc Sắc giới: thuần túy là Ý nghiệp, do công trình hành thiền, phân theo các chi thiền thành năm bậc.",
                "Nghiệp Thiện thuộc Vô sắc giới: cũng là Ý nghiệp do hành thiền, phân theo đề mục thiền thành bốn bậc.",
                "Tài liệu cũng liệt kê 10 việc thiện Dục giới (Phước hành tông): Bố thí, Trì giới, Hành thiền, Lễ bái bậc trưởng thượng, Phục vụ, Hồi hướng phước báu, Thọ hưởng phước báu, Nghe Pháp, Giảng Pháp, và Củng cố Chánh kiến.",
            ],
            "keyTerms": [
                {"id": "TERM_KAMAVACARA_K", "term": "Nghiệp Thiện Dục giới", "pali": "Kāmāvacarakusala", "meaning": "8 tâm Đại thiện + Tư"},
                {"id": "TERM_RUPAVACARA_K", "term": "Nghiệp Thiện Sắc giới", "pali": "Rūpāvacarakusala", "meaning": "Ý nghiệp do thiền Sắc giới, 5 bậc"},
                {"id": "TERM_ARUPAVACARA_K", "term": "Nghiệp Thiện Vô sắc giới", "pali": "Arūpāvacarakusala", "meaning": "Ý nghiệp do thiền Vô sắc, 4 bậc"},
            ],
            "sourceRefs": [
                ref(NGHIEP, 3, "Nghiệp Thiện Dục giới: ba môn; Bố thí, Trì giới, Hành thiền"),
                ref(NGHIEP, 4, "Nghiệp Thiện Sắc giới/Vô sắc giới; 10 việc thiện"),
                ref(SODO, 14, "Lãnh vực nghiệp — Nghiệp Bất thiện thuộc Dục giới"),
                ref(SODO, 15, "Nghiệp Thiện thuộc Dục giới"),
            ],
        },
        {
            "id": "M6_S07",
            "title": "Nghiệp theo Môn: Thân, Khẩu, Ý",
            "summary": "10 bất thiện nghiệp và 10 thiện nghiệp phân theo ba môn.",
            "body": [
                "Thân môn bất thiện có 3: Sát sanh (Pāṇātipāta), Trộm cắp (Adinnādāna), Tà hạnh trong dục lạc (Kāmesumicchācāra).",
                "Khẩu môn bất thiện có 4: Nói dối (Musāvāda), Nói đâm thọc (Pisuṇavācā), Nói thô lỗ (Pharusavācā), Nói nhảm/vô ích (Samphappalāpa).",
                "Ý môn bất thiện có 3: Tham ác (Abhijjhā), Sân hận (Byāpāda), Tà kiến (Micchādiṭṭhi). Đây là hành động tinh thần thực hiện xuyên qua chính cái tâm, không cần thân hay khẩu.",
                "Về căn: Sát sanh, nói thô lỗ và Sân hận bắt nguồn từ căn Sân; Tà hạnh, Tham ái và Tà kiến bắt nguồn từ căn Tham; bốn nghiệp còn lại có thể bắt nguồn từ cả hai căn.",
                "Về phía thiện, thân nghiệp thiện là tránh xa 3 điều trên (thực hiện bằng tâm sở Chánh nghiệp, Chánh mạng); ngữ nghiệp thiện là tránh xa 4 lời bất thiện (Chánh ngữ, Chánh mạng); ý nghiệp thiện gồm Vô tham (Anabhijjhā), Vô sân (Abyāpāda) và Chánh kiến (Sammādiṭṭhi).",
            ],
            "keyTerms": [
                {"id": "TERM_PANATIPATA", "term": "Sát sanh", "pali": "Pāṇātipāta", "meaning": "Thân nghiệp bất thiện thứ nhất"},
                {"id": "TERM_MUSAVADA", "term": "Nói dối", "pali": "Musāvāda", "meaning": "Khẩu nghiệp bất thiện thứ nhất"},
                {"id": "TERM_ABHIJJHA", "term": "Tham ác", "pali": "Abhijjhā", "meaning": "Ý nghiệp bất thiện"},
                {"id": "TERM_SAMMADITTHI", "term": "Chánh kiến", "pali": "Sammādiṭṭhi", "meaning": "Ý nghiệp thiện — quan kiến chân chánh"},
            ],
            "sourceRefs": [
                ref(NGHIEP, 2, "Thân nghiệp — kāyakamma"),
                ref(NGHIEP, 3, "Khẩu nghiệp, Ý nghiệp và các căn"),
                ref(SODO, 14, "Bất thiện nghiệp theo Môn"),
                ref(SODO, 15, "Thiện nghiệp theo Môn"),
            ],
        },
        {
            "id": "M6_S08",
            "title": "Nghiệp liên hệ với Tâm",
            "summary": "Chi pháp: nghiệp nào do tâm nào, và cho tâm quả tục sinh nào.",
            "body": [
                "Nhân tạo Sanh nghiệp gồm 28 tâm: 11 tâm Bất thiện (12 tâm Bất thiện trừ tâm Si Thọ xả Phóng dật, vì tâm này không cho quả tục sinh), 8 tâm Thiện Dục giới Tịnh hảo, 5 tâm Thiện Sắc giới, 4 tâm Thiện Vô sắc giới.",
                "Tâm quả tục sinh có 19: 2 tâm Quan sát vô nhân thọ xả (quả thiện và quả bất thiện), 8 tâm Quả thiện Dục giới Tịnh hảo, 5 tâm Quả Sắc giới, 4 tâm Quả Vô sắc giới.",
                "Tư tâm sở trong 11 tâm Bất thiện cho tâm Quan sát Thọ xả Quả Bất thiện Vô nhân — tái sanh làm người khổ (súc sanh, ngạ quỷ, a-tu-la, địa ngục).",
                "Tư tâm sở trong 4 tâm Thiện Dục giới Ly trí mà thiếu Tư thì cho tâm Quan sát Thọ xả Quả thiện Vô nhân — tái sanh làm người lạc vô nhân; đủ Tư thì làm người Nhị nhân. Tư trong 4 tâm Thiện hợp trí đủ Tư thì tái sanh làm người Tam nhân.",
                "Nghiệp cũng làm cho Sắc sanh khởi: có 18 sắc do nghiệp tạo, gồm 8 sắc Bất ly, 5 sắc Thần kinh, 1 sắc Hư không, 1 sắc Mạng quyền, 1 sắc Ý vật và 2 sắc Tánh.",
            ],
            "keyTerms": [
                {"id": "TERM_TIHETUKA", "term": "Người Tam nhân", "pali": "Tihetuka", "meaning": "Tục sinh với 3 nhân (vô tham, vô sân, vô si)"},
                {"id": "TERM_DVIHETUKA", "term": "Người Nhị nhân", "pali": "Dvihetuka", "meaning": "Tục sinh với 2 nhân, thiếu vô si"},
                {"id": "TERM_KAMMAJA_RUPA", "term": "Sắc nghiệp", "pali": "Kammaja-rūpa", "meaning": "18 sắc do nghiệp sanh"},
            ],
            "sourceRefs": [
                ref(SODO, 2, "Chi pháp nhân Sanh nghiệp: 28 tâm; tâm quả tục sinh 19"),
                ref(SODO, 3, "Tư tâm sở dẫn tái sanh; Nghiệp làm cho Sắc sanh khởi — 18 sắc"),
            ],
        },
    ],
    "reviewCards": [
        {"id": "M6_R01", "front": "Pháp bản thể của Nghiệp là gì?", "back": "Tâm sở Tư (Cetanā) — sự cố ý tạo tác. “Cetanāhaṃ, bhikkhave, kammaṃ vadāmi”.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_R02", "front": "Nghiệp sanh khởi qua mấy môn? Môn nào tối trọng?", "back": "Ba môn: Thân, Khẩu, Ý. Ý nghiệp là tối trọng.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_R03", "front": "Kammacatukka gồm bao nhiêu loại, chia mấy nhóm?", "back": "16 loại, chia 4 nhóm: phận sự, năng lực, thời gian trổ quả, lãnh vực trổ quả.", "sourceRefs": [ref(SODO, 1)]},
        {"id": "M6_R04", "front": "Bốn nghiệp theo phận sự là gì?", "back": "Sanh nghiệp (Janaka), Trì nghiệp (Upatthambhaka), Chướng nghiệp (Upapīḷaka), Đoạn nghiệp (Upaghātaka).", "sourceRefs": [ref(SODO, 1), ref(NGHIEP, 2)]},
        {"id": "M6_R05", "front": "Sanh nghiệp làm phận sự gì?", "back": "Tạo Danh uẩn và Sắc uẩn thời tục sinh, làm cho Thức tục sinh (Paṭisandhi viññāṇa) sanh lên.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_R06", "front": "Chướng nghiệp khác Đoạn nghiệp thế nào?", "back": "Chướng nghiệp cản trở, làm suy giảm và chậm trễ Sanh nghiệp; Đoạn nghiệp mạnh hơn, cắt đứt và tiêu diệt Sanh nghiệp.", "sourceRefs": [ref(SODO, 5)]},
        {"id": "M6_R07", "front": "Chướng nghiệp có mặt ở cõi nào?", "back": "Không có trong cõi Sắc giới và cõi Vô sắc giới.", "sourceRefs": [ref(SODO, 5)]},
        {"id": "M6_R08", "front": "Bốn nghiệp theo thứ tự trổ quả (năng lực)?", "back": "Trọng nghiệp (Garuka), Cận tử nghiệp (Āsanna), Thường nghiệp (Āciṇṇa), Khinh thiểu nghiệp (Kaṭattā).", "sourceRefs": [ref(SODO, 1), ref(NGHIEP, 2)]},
        {"id": "M6_R09", "front": "Ngũ nghịch đại tội (Ānantariyakamma) gồm những gì?", "back": "Giết mẹ, giết cha, giết A-la-hán, chia rẽ Tăng, làm chảy máu thân Phật.", "sourceRefs": [ref(SODO, 6)]},
        {"id": "M6_R10", "front": "Ác trọng nghiệp nào mạnh nhất?", "back": "Tà kiến nhất định (Niyatamicchādiṭṭhikamma), kế đến là chia rẽ Tăng.", "sourceRefs": [ref(SODO, 6)]},
        {"id": "M6_R11", "front": "Trọng nghiệp thiện có chi pháp là gì?", "back": "9 tâm Thiện Đáo đại (5 thiện Sắc giới + 4 thiện Vô sắc giới).", "sourceRefs": [ref(SODO, 7)]},
        {"id": "M6_R12", "front": "Nghiệp thời được xác định căn cứ vào đâu?", "back": "Căn cứ nơi lộ tâm Đổng lực — 7 sát-na Javana.", "sourceRefs": [ref(SODO, 10)]},
        {"id": "M6_R13", "front": "Sát-na Đổng lực thứ 1 cho loại nghiệp nào?", "back": "Hiện báo nghiệp (Diṭṭhadhammavedanīyakamma) — cho quả ngay kiếp hiện tại.", "sourceRefs": [ref(SODO, 10)]},
        {"id": "M6_R14", "front": "Sát-na Đổng lực thứ 7 cho loại nghiệp nào?", "back": "Sanh báo nghiệp (Upapajjavedanīyakamma) — cho quả trong kiếp kế.", "sourceRefs": [ref(SODO, 10), ref(SODO, 11)]},
        {"id": "M6_R15", "front": "Các sát-na Đổng lực 2–6 cho loại nghiệp nào?", "back": "Hậu báo nghiệp (Aparāpariyavedanīyakamma) — cho quả từ kiếp thứ 3 đến khi Niết-bàn. Sát-na thứ 4 mạnh nhất.", "sourceRefs": [ref(SODO, 10), ref(SODO, 12)]},
        {"id": "M6_R16", "front": "Vô hiệu nghiệp (Ahosikamma) là gì?", "back": "Nghiệp đã tạo mà không còn cơ hội cho quả. Riêng Hậu báo nghiệp không tiêu hoại nếu chưa cho quả.", "sourceRefs": [ref(SODO, 13)]},
        {"id": "M6_R17", "front": "Bốn lãnh vực trổ quả của Nghiệp?", "back": "Nghiệp Bất thiện, Nghiệp Thiện Dục giới, Nghiệp Thiện Sắc giới, Nghiệp Thiện Vô sắc giới.", "sourceRefs": [ref(SODO, 1), ref(NGHIEP, 2)]},
        {"id": "M6_R18", "front": "Mười bất thiện nghiệp phân theo môn thế nào?", "back": "Thân 3 (sát sanh, trộm cắp, tà hạnh); Khẩu 4 (nói dối, đâm thọc, thô lỗ, vô ích); Ý 3 (tham ác, sân ác, tà kiến).", "sourceRefs": [ref(SODO, 14), ref(NGHIEP, 2)]},
        {"id": "M6_R19", "front": "Nhân tạo Sanh nghiệp gồm bao nhiêu tâm?", "back": "28 tâm: 11 tâm Bất thiện, 8 Thiện Dục giới Tịnh hảo, 5 Thiện Sắc giới, 4 Thiện Vô sắc giới.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_R20", "front": "Vì sao tâm Si Thọ xả Phóng dật không tạo Sanh nghiệp?", "back": "Vì tâm này không thể cho quả tục sinh, không cho Thức tái tục được.", "sourceRefs": [ref(SODO, 2)]},
    ],
    "quizSeeds": [
        {"id": "M6_Q01", "type": "mcq", "question": "Pháp bản thể của Nghiệp (Kamma) là tâm sở nào?", "correctAnswer": "Tâm sở Tư (Cetanā)", "distractors": ["Tâm sở Xúc (Phassa)", "Tâm sở Thọ (Vedanā)", "Tâm sở Tưởng (Saññā)"], "explanation": "Đức Phật dạy “Cetanāhaṃ, bhikkhave, kammaṃ vadāmi” — Cố ý là Nghiệp.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_Q02", "type": "mcq", "question": "Trong ba môn tạo nghiệp, môn nào được xem là tối trọng?", "correctAnswer": "Ý môn", "distractors": ["Thân môn", "Khẩu môn", "Cả ba ngang nhau"], "explanation": "Tài liệu ghi rõ: Ý nghiệp là TỐI TRỌNG.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_Q03", "type": "mcq", "question": "Kammacatukka phân Nghiệp thành bao nhiêu loại?", "correctAnswer": "16 loại, chia 4 nhóm", "distractors": ["12 loại, chia 3 nhóm", "20 loại, chia 5 nhóm", "8 loại, chia 2 nhóm"], "explanation": "Sơ đồ Nghiệp: có 16 loại phân thành 4 nhóm, mỗi nhóm 4 loại.", "sourceRefs": [ref(SODO, 1)]},
        {"id": "M6_Q04", "type": "mcq", "question": "Nghiệp nào tạo nên Danh uẩn và Sắc uẩn trong thời tục sinh?", "correctAnswer": "Sanh nghiệp (Janakakamma)", "distractors": ["Trì nghiệp (Upatthambhakakamma)", "Chướng nghiệp (Upapīḷakakamma)", "Đoạn nghiệp (Upaghātakakamma)"], "explanation": "Sanh nghiệp làm cho tâm quả dị thục sanh lên trong thời tái tục, tức Thức tục sinh.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_Q05", "type": "mcq", "question": "Nghiệp nào có lực mạnh hơn, cắt đứt cả Sanh nghiệp lẫn Trì nghiệp?", "correctAnswer": "Đoạn nghiệp (Upaghātakakamma)", "distractors": ["Chướng nghiệp (Upapīḷakakamma)", "Trì nghiệp (Upatthambhakakamma)", "Khinh thiểu nghiệp (Kaṭattākamma)"], "explanation": "Đoạn nghiệp có lực mạnh hơn Chướng nghiệp: Chướng nghiệp chỉ cản trở, Đoạn nghiệp diệt trừ Sanh nghiệp.", "sourceRefs": [ref(SODO, 5)]},
        {"id": "M6_Q06", "type": "mcq", "question": "Chướng nghiệp KHÔNG có mặt trong cõi nào?", "correctAnswer": "Cõi Sắc giới và Vô sắc giới", "distractors": ["Cõi Dục giới", "Bốn cõi khổ", "Cõi người"], "explanation": "Tài liệu ghi: Nghiệp cản trở (Chướng nghiệp) không có trong cõi Sắc hay cõi Vô sắc.", "sourceRefs": [ref(SODO, 5)]},
        {"id": "M6_Q07", "type": "mcq", "question": "Ngũ nghịch đại tội thuộc loại nghiệp nào?", "correctAnswer": "Trọng nghiệp (Garukakamma)", "distractors": ["Cận tử nghiệp (Āsannakamma)", "Thường nghiệp (Āciṇṇakamma)", "Khinh thiểu nghiệp (Kaṭattākamma)"], "explanation": "Ngũ nghịch đại tội là Vô gián nghiệp (Ānantariyakamma), thuộc nhóm Trọng nghiệp về phía bất thiện.", "sourceRefs": [ref(SODO, 6)]},
        {"id": "M6_Q08", "type": "mcq", "question": "Theo tài liệu, ác trọng nghiệp nào có sức mạnh lớn nhất?", "correctAnswer": "Tà kiến nhất định (Niyatamicchādiṭṭhikamma)", "distractors": ["Giết mẹ", "Giết cha", "Làm chảy máu thân Phật"], "explanation": "Thứ tự sức mạnh: mạnh nhất là Tà kiến nhất định, thứ nhì chia rẽ Tăng, thứ ba làm chảy máu thân Phật.", "sourceRefs": [ref(SODO, 6)]},
        {"id": "M6_Q09", "type": "mcq", "question": "Chi pháp của Trọng nghiệp thiện là gì?", "correctAnswer": "9 tâm Thiện Đáo đại", "distractors": ["8 tâm Đại thiện Dục giới", "12 tâm Bất thiện", "8 tâm Siêu thế"], "explanation": "Trọng nghiệp thiện là 9 tâm Thiện Đáo đại (5 Sắc giới + 4 Vô sắc giới). Siêu thế tuy cao thượng nhưng không xếp vào vì tiêu trừ nghiệp hữu.", "sourceRefs": [ref(SODO, 7)]},
        {"id": "M6_Q10", "type": "mcq", "question": "Nghiệp thời (Pākakālakamma) được xác định căn cứ nơi đâu?", "correctAnswer": "7 sát-na Đổng lực (Javana) trong lộ tâm", "distractors": ["3 sát-na Hộ kiếp", "2 sát-na Na cảnh", "Tâm Tục sinh"], "explanation": "Nghiệp cho quả theo thời gian tùy theo căn cứ nơi lộ tâm đổng tốc — 7 sát na Javana.", "sourceRefs": [ref(SODO, 10)]},
        {"id": "M6_Q11", "type": "mcq", "question": "Sát-na Đổng lực thứ nhất cho loại nghiệp nào?", "correctAnswer": "Hiện báo nghiệp — cho quả ngay kiếp hiện tại", "distractors": ["Sanh báo nghiệp — cho quả kiếp kế", "Hậu báo nghiệp — từ kiếp thứ 3", "Vô hiệu nghiệp"], "explanation": "Sát-na thứ 1 yếu nhất vì sanh đầu tiên, không có sát-na đồng loại hỗ trợ, nên chỉ cho quả trong kiếp hiện tại.", "sourceRefs": [ref(SODO, 10)]},
        {"id": "M6_Q12", "type": "mcq", "question": "Sát-na Đổng lực thứ 7 cho loại nghiệp nào?", "correctAnswer": "Sanh báo nghiệp (Upapajjavedanīyakamma)", "distractors": ["Hiện báo nghiệp", "Hậu báo nghiệp", "Vô hiệu nghiệp"], "explanation": "Sát-na thứ 7 yếu thứ nhì vì cận kề sự diệt, chỉ cho quả trong kiếp kế tới.", "sourceRefs": [ref(SODO, 10)]},
        {"id": "M6_Q13", "type": "mcq", "question": "Trong 7 sát-na Đổng lực, sát-na nào mạnh nhất?", "correctAnswer": "Sát-na thứ 4", "distractors": ["Sát-na thứ 1", "Sát-na thứ 7", "Sát-na thứ 2"], "explanation": "Sát-na thứ 4 mạnh nhất vì ở giai đoạn cực thịnh và là sát-na Quyền.", "sourceRefs": [ref(SODO, 10)]},
        {"id": "M6_Q14", "type": "mcq", "question": "Nhân tạo Sanh nghiệp gồm bao nhiêu tâm?", "correctAnswer": "28 tâm", "distractors": ["19 tâm", "12 tâm", "8 tâm"], "explanation": "28 tâm = 11 tâm Bất thiện + 8 Thiện Dục giới Tịnh hảo + 5 Thiện Sắc giới + 4 Thiện Vô sắc giới.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_Q15", "type": "mcq", "question": "Vì sao chỉ có 11 (không phải 12) tâm Bất thiện làm nhân Sanh nghiệp?", "correctAnswer": "Vì tâm Si Thọ xả Phóng dật không cho quả tục sinh", "distractors": ["Vì tâm Sân không cho quả", "Vì tâm Tham ly tà không cho quả", "Vì tâm Si Hoài nghi không cho quả"], "explanation": "Trừ tâm Si Thọ xả Phóng dật vì tâm này không thể cho quả tục sinh, không cho Thức tái tục được.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_Q16", "type": "mcq", "question": "Có bao nhiêu tâm quả làm việc tục sinh?", "correctAnswer": "19 tâm", "distractors": ["28 tâm", "12 tâm", "11 tâm"], "explanation": "19 tâm = 2 Quan sát vô nhân thọ xả + 8 Quả thiện Dục giới Tịnh hảo + 5 Quả Sắc giới + 4 Quả Vô sắc giới.", "sourceRefs": [ref(SODO, 2)]},
        {"id": "M6_Q17", "type": "mcq", "question": "Nghiệp làm cho bao nhiêu sắc pháp sanh khởi?", "correctAnswer": "18 sắc", "distractors": ["15 sắc", "13 sắc", "12 sắc"], "explanation": "18 sắc do nghiệp: 8 sắc Bất ly + 5 sắc Thần kinh + 1 sắc Hư không + 1 sắc Mạng quyền + 1 sắc Ý vật + 2 sắc Tánh.", "sourceRefs": [ref(SODO, 3)]},
        {"id": "M6_Q18", "type": "mcq", "question": "Khẩu nghiệp bất thiện gồm mấy điều?", "correctAnswer": "4 điều", "distractors": ["3 điều", "5 điều", "7 điều"], "explanation": "Nói dối, nói đâm thọc, nói thô lỗ, nói nhảm/vô ích.", "sourceRefs": [ref(NGHIEP, 3), ref(SODO, 14)]},
    ],
}


M8_VI = {
    "title": "Thập Nhị Duyên Khởi (Paṭiccasamuppāda)",
    "description": "12 chi duyên khởi, ba thời, bốn phân hạng, ba luân chuyển và hai nhân gốc.",
    "translationStatus": "reviewed",
    "lessonSections": [
        {
            "id": "M8_S01",
            "title": "Paṭiccasamuppāda là gì?",
            "summary": "Định luật tùy thuộc phát sanh: cái này có thì cái kia có.",
            "body": [
                "Paṭicca nghĩa là “bởi vì, vì lẽ”; Samuppāda nghĩa là “phát sanh, xuất phát”. Paṭiccasamuppāda là định luật tùy thuộc phát sanh, duyên khởi.",
                "Định nghĩa Pāli: “Paccayaṃ paṭicca samuppajjatīti paṭiccasamuppādo” — cái gì sanh ra được là nhờ bởi duyên thì gọi là Duyên sinh.",
                "Nguyên tắc căn bản: “Imasmiṃ sati, idaṃ hoti; imasmiṃ asati, idaṃ na hoti” — cái này có thì cái kia có; cái này không thì cái kia không.",
                "Toát yếu về Duyên (Paccaya-saṅgaha-vibhāgo) có hai phần: Định luật Tùy thuộc Phát sanh (Paṭiccasamuppāda-naya) và Định luật Duyên hệ Tương quan (Paṭṭhāna-naya). Phần thứ nhất chỉ nêu sự phát sanh của một trạng thái tùy thuộc nơi một trạng thái khác trước đó.",
            ],
            "keyTerms": [
                {"id": "TERM_PATICCA", "term": "Duyên khởi", "pali": "Paṭiccasamuppāda", "meaning": "Định luật tùy thuộc phát sanh"},
                {"id": "TERM_PATTHANA", "term": "Duyên hệ tương quan", "pali": "Paṭṭhāna", "meaning": "Định luật về các duyên hệ"},
                {"id": "TERM_PACCAYA", "term": "Duyên", "pali": "Paccaya", "meaning": "Điều kiện làm cho pháp khác sanh khởi"},
            ],
            "sourceRefs": [
                ref(DUYEN, 3, "Paccaya-saṅgaha-vibhāgo: hai phần Paṭiccasamuppāda và Paṭṭhāna"),
                ref(DUYEN, 6, "Định nghĩa Paṭicca + Samuppāda, Imasmiṃ sati idaṃ hoti"),
            ],
        },
        {
            "id": "M8_S02",
            "title": "Mười hai chi duyên khởi",
            "summary": "Từ Vô minh đến Lão Tử: chuỗi 12 chi làm phát sanh toàn khối đau khổ.",
            "body": [
                "Tùy thuộc nơi Vô minh (Avijjā) phát sanh Hành (Saṅkhārā). Tùy thuộc nơi Hành phát sanh Thức tái sanh (Viññāṇa). Tùy thuộc nơi Thức phát sanh Danh–Sắc (Nāmarūpa).",
                "Tùy thuộc nơi Danh–Sắc phát sanh Lục nhập (Saḷāyatana). Tùy thuộc nơi Lục nhập phát sanh Xúc (Phassa). Tùy thuộc nơi Xúc phát sanh Thọ (Vedanā).",
                "Tùy thuộc nơi Thọ phát sanh Ái (Taṇhā). Tùy thuộc nơi Ái phát sanh Thủ (Upādāna). Tùy thuộc nơi Thủ phát sanh Hữu (Bhava).",
                "Tùy thuộc nơi Hữu có Sanh (Jāti). Tùy thuộc nơi Sanh có Lão Tử (Jarāmaraṇa), Sầu muộn, Ta thán, Đau khổ, Buồn rầu và Thất vọng. Như vậy phát sanh trọn vẹn toàn khối đau khổ.",
                "Đúng 12 chi là: Vô minh, Hành, Thức, Danh–Sắc, Lục nhập, Xúc, Thọ, Ái, Thủ, Hữu, Sanh, Lão Tử. Các từ Sầu muộn, Ta thán v.v. là hậu quả (nissandaphala) của Sanh, không tính thành chi riêng.",
            ],
            "keyTerms": [
                {"id": "TERM_AVIJJA", "term": "Vô minh", "pali": "Avijjā", "meaning": "Không thấu rõ Tứ Diệu Đế"},
                {"id": "TERM_SANKHARA", "term": "Hành", "pali": "Saṅkhārā", "meaning": "Tâm sở Tư tạo tác"},
                {"id": "TERM_VINNANA", "term": "Thức", "pali": "Viññāṇa", "meaning": "Thức tái sanh"},
                {"id": "TERM_NAMARUPA", "term": "Danh Sắc", "pali": "Nāmarūpa", "meaning": "Tâm và Sắc"},
                {"id": "TERM_SALAYATANA", "term": "Lục nhập", "pali": "Saḷāyatana", "meaning": "Sáu xứ / sáu căn"},
                {"id": "TERM_JARAMARANA", "term": "Lão Tử", "pali": "Jarāmaraṇa", "meaning": "Già và chết"},
            ],
            "sourceRefs": [
                ref(DUYEN, 2, "Bản kệ 12 chi Pāli – Việt – Anh"),
                ref(DUYEN, 3, "Tattha avijjāpaccayā saṅkhārā… bản dịch Việt"),
                ref(DUYEN, 4, "Dvādasaṅgāni — liệt kê đúng 12 chi"),
                ref(DUYEN, 6, "Bảng 12 chi Duyên sinh"),
            ],
        },
        {
            "id": "M8_S03",
            "title": "Ba thời — Tayo addhā",
            "summary": "Quá khứ 2 chi, hiện tại 8 chi, vị lai 2 chi (Sanh, Lão Tử).",
            "body": [
                "Vô minh và Hành thuộc về thời Quá khứ.",
                "Tám chi ở khoảng giữa — Thức, Danh–Sắc, Lục nhập, Xúc, Thọ, Ái, Thủ, Hữu — thuộc về thời Hiện tại.",
                "Sanh và Lão Tử thuộc về thời Vị lai.",
                "Như vậy có ba thời kỳ (tayo addhā) trải trên chuỗi 12 chi.",
            ],
            "keyTerms": [
                {"id": "TERM_TAYO_ADDHA", "term": "Ba thời", "pali": "Tayo addhā", "meaning": "Quá khứ, hiện tại, vị lai"},
            ],
            "sourceRefs": [ref(DUYEN, 4, "Avijjā, saṅkhārā atīto addhā… tayo addhā")],
        },
        {
            "id": "M8_S04",
            "title": "Hai mươi phương cách, bốn phân hạng, ba mối liên hệ",
            "summary": "5 nhân quá khứ → 5 quả hiện tại → 5 nhân hiện tại → 5 quả vị lai.",
            "body": [
                "Bốn phân hạng (catusaṅkhepa): (1) năm nhân thuộc quá khứ, (2) năm quả trong hiện tại, (3) năm nhân trong hiện tại, (4) năm quả thuộc vị lai.",
                "Cộng lại thành hai mươi phương cách (vīsatākārā) và ba mối liên hệ (tisandhi) nối giữa bốn phân hạng ấy.",
                "Tài liệu giải thích cách quy đổi: khi đề cập Vô minh và Hành thì Ái, Thủ, Hữu cũng được bao hàm; ngược lại khi đề cập Ái, Thủ, Hữu thì Vô minh và Hành cũng được bao hàm. Khi đề cập Sanh, Lão Tử thì năm quả (Thức, Danh–Sắc, Lục nhập, Xúc, Thọ) cũng được bao hàm.",
            ],
            "keyTerms": [
                {"id": "TERM_VISATAKARA", "term": "Hai mươi phương cách", "pali": "Vīsatākārā", "meaning": "20 thể thức nhân-quả"},
                {"id": "TERM_TISANDHI", "term": "Ba mối liên hệ", "pali": "Tisandhi", "meaning": "3 chỗ nối giữa nhân và quả"},
                {"id": "TERM_CATUSANKHEPA", "term": "Bốn phân hạng", "pali": "Catusaṅkhepa", "meaning": "4 nhóm nhân-quả theo thời"},
            ],
            "sourceRefs": [
                ref(DUYEN, 4, "Atīte hetavo pañca… vīsatākārā, tisandhi, catusaṅkhepā"),
            ],
        },
        {
            "id": "M8_S05",
            "title": "Ba luân chuyển và hai nhân gốc",
            "summary": "Phiền não luân, Nghiệp luân, Quả luân; hai gốc là Vô minh và Ái.",
            "body": [
                "Phiền não luân (Kilesavaṭṭa): Vô minh, Ái và Thủ.",
                "Nghiệp luân (Kammavaṭṭa): Hành, và một phần của Hữu được gọi là Nghiệp hữu (kammabhava).",
                "Quả luân (Vipākavaṭṭa): một phần của Hữu được gọi là Sanh hữu (upapattibhava), cùng các chi còn lại.",
                "Hai nhân gốc (dve mūlāni) cần được hiểu là Vô minh và Ái dục.",
                "Về chiều đoạn diệt, tài liệu tóm lược: “Bằng cách tận diệt những nhân này, Vòng Quanh luân chuyển chấm dứt.” Vô minh xuất phát từ những nhiễm ô (āsava) và tăng trưởng theo sự áp bức của già và chết.",
            ],
            "keyTerms": [
                {"id": "TERM_KILESAVATTA", "term": "Phiền não luân", "pali": "Kilesavaṭṭa", "meaning": "Vòng phiền não: Vô minh, Ái, Thủ"},
                {"id": "TERM_KAMMAVATTA", "term": "Nghiệp luân", "pali": "Kammavaṭṭa", "meaning": "Vòng nghiệp: Hành và Nghiệp hữu"},
                {"id": "TERM_VIPAKAVATTA", "term": "Quả luân", "pali": "Vipākavaṭṭa", "meaning": "Vòng quả: Sanh hữu và các chi quả"},
                {"id": "TERM_DVE_MULANI", "term": "Hai nhân gốc", "pali": "Dve mūlāni", "meaning": "Vô minh và Ái"},
            ],
            "sourceRefs": [
                ref(DUYEN, 5, "Avijjā taṇhūpādāna ca kilesavaṭṭaṃ… tīṇi vaṭṭāni; dve mūlāni"),
            ],
        },
        {
            "id": "M8_S06",
            "title": "Chi 1 — Vô minh (Avijjā)",
            "summary": "Không thấu rõ Tứ Diệu Đế; căn gốc là tâm sở Si (Moha).",
            "body": [
                "Vô minh là không sáng suốt, không hiểu biết, không nhận chân ra sự thật của vạn hữu.",
                "Kinh văn định nghĩa: không hiểu về Khổ, không hiểu về Khổ tập, không hiểu về Khổ diệt, không hiểu về con đường đưa đến Khổ diệt — đây gọi là Vô minh.",
                "Thế gian là Vô thường, Khổ, Vô ngã mà cho là Thường, Lạc, Ngã — đó là Vô minh. Không hiểu 12 Duyên khởi cũng là Vô minh.",
                "Căn gốc của Vô minh là tâm sở Si (Moha), từ căn “Muh” nghĩa là mê mờ, lầm lạc. Moha luôn có mặt trong mọi tâm bất thiện và là một trong ba nhân bất thiện: Tham, Sân, Si.",
                "Đối nghịch với Vô minh là Minh (Vijjā): sáng suốt, tuệ tri Tứ Diệu Đế, thấu rõ lý Duyên khởi.",
            ],
            "keyTerms": [
                {"id": "TERM_MOHA_M8", "term": "Si", "pali": "Moha", "meaning": "Căn gốc của Vô minh"},
                {"id": "TERM_VIJJA", "term": "Minh", "pali": "Vijjā", "meaning": "Trí sáng suốt, đối nghịch Vô minh"},
            ],
            "sourceRefs": [ref(DUYEN, 7, "Avijjāpaccayā saṅkhārā — Vô minh duyên Hành")],
        },
        {
            "id": "M8_S07",
            "title": "Chi 2 — Hành (Saṅkhārā)",
            "summary": "Ba loại Hành: Phi phúc hành, Phúc hành, Bất động hành.",
            "body": [
                "Hành là cái gì tạo thành, tạo sanh, tạo tác. Pháp bản thể của Hành là tâm sở Tư (Cetanā) — một trong 7 tâm sở biến hành.",
                "Phi phúc hành (Apuññābhisaṅkhāra): tâm sở Tư phối hợp trong 1 trong 12 tâm Bất thiện, xui khiến tạo 10 bất thiện nghiệp qua thân, khẩu, ý.",
                "Phúc hành (Puññābhisaṅkhāra): tâm sở Tư đồng sanh trong 8 tâm Thiện Dục giới và 5 tâm Thiện Sắc giới; tạo ra các tâm quả thiện Dục giới, quả thiện Sắc giới và Sắc nghiệp thiện.",
                "Bất động hành (Āneñjābhisaṅkhāra): tâm sở Tư đồng sanh trong 4 tâm Thiện Vô sắc giới, tạo ra các tâm Quả Vô sắc giới.",
                "Phận sự của tâm sở Tư: đôn đốc xúi giục các pháp, làm cho các pháp đồng sanh nắm bắt cảnh, hoàn tất nhiệm vụ và sắp đặt các pháp đồng sanh làm theo.",
            ],
            "keyTerms": [
                {"id": "TERM_APUNNA", "term": "Phi phúc hành", "pali": "Apuññābhisaṅkhāra", "meaning": "Hành bất thiện — 12 tâm Bất thiện"},
                {"id": "TERM_PUNNA", "term": "Phúc hành", "pali": "Puññābhisaṅkhāra", "meaning": "Hành thiện Dục giới và Sắc giới"},
                {"id": "TERM_ANENJA", "term": "Bất động hành", "pali": "Āneñjābhisaṅkhāra", "meaning": "Hành thiện Vô sắc giới"},
            ],
            "sourceRefs": [ref(DUYEN, 8, "Hành — Saṅkhārā: 3 loại và chi pháp")],
        },
    ],
    "reviewCards": [
        {"id": "M8_R01", "front": "Paṭicca + Samuppāda nghĩa là gì?", "back": "Paṭicca: bởi vì, vì lẽ. Samuppāda: phát sanh, xuất phát. Tức “tùy thuộc phát khởi”.", "sourceRefs": [ref(DUYEN, 6)]},
        {"id": "M8_R02", "front": "Nguyên tắc “Imasmiṃ sati, idaṃ hoti” nghĩa là gì?", "back": "Cái này có thì cái kia có; cái này không thì cái kia không.", "sourceRefs": [ref(DUYEN, 6)]},
        {"id": "M8_R03", "front": "Toát yếu về Duyên gồm mấy phần?", "back": "Hai phần: Định luật Tùy thuộc Phát sanh (Paṭiccasamuppāda) và Định luật Duyên hệ Tương quan (Paṭṭhāna).", "sourceRefs": [ref(DUYEN, 3)]},
        {"id": "M8_R04", "front": "Kể đủ 12 chi duyên khởi.", "back": "Vô minh, Hành, Thức, Danh–Sắc, Lục nhập, Xúc, Thọ, Ái, Thủ, Hữu, Sanh, Lão Tử.", "sourceRefs": [ref(DUYEN, 4), ref(DUYEN, 6)]},
        {"id": "M8_R05", "front": "Vì sao Sầu, Ta thán, Đau khổ… không tính là chi riêng?", "back": "Vì chúng là hậu quả (nissandaphala) của Sanh, không phải chi độc lập.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_R06", "front": "Chi nào thuộc thời quá khứ?", "back": "Vô minh và Hành.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_R07", "front": "Chi nào thuộc thời vị lai?", "back": "Sanh và Lão Tử.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_R08", "front": "Có bao nhiêu chi thuộc thời hiện tại?", "back": "Tám chi: Thức, Danh–Sắc, Lục nhập, Xúc, Thọ, Ái, Thủ, Hữu.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_R09", "front": "Bốn phân hạng (catusaṅkhepa) là gì?", "back": "5 nhân quá khứ, 5 quả hiện tại, 5 nhân hiện tại, 5 quả vị lai.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_R10", "front": "Vīsatākārā và tisandhi nghĩa là gì?", "back": "20 phương cách nhân-quả và 3 mối liên hệ nối giữa bốn phân hạng.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_R11", "front": "Ba luân chuyển (tīṇi vaṭṭāni) gồm những gì?", "back": "Phiền não luân (Vô minh, Ái, Thủ); Nghiệp luân (Hành + Nghiệp hữu); Quả luân (Sanh hữu và các chi quả).", "sourceRefs": [ref(DUYEN, 5)]},
        {"id": "M8_R12", "front": "Hai nhân gốc (dve mūlāni) của vòng luân hồi?", "back": "Vô minh (Avijjā) và Ái (Taṇhā).", "sourceRefs": [ref(DUYEN, 5)]},
        {"id": "M8_R13", "front": "Vòng luân chuyển chấm dứt bằng cách nào?", "back": "Bằng cách tận diệt những nhân ấy — “Tesam eva ca mūlānaṃ nirodhena nirujjhati”.", "sourceRefs": [ref(DUYEN, 5)]},
        {"id": "M8_R14", "front": "Định nghĩa Vô minh theo kinh văn?", "back": "Không hiểu về Khổ, Khổ tập, Khổ diệt, và con đường đưa đến Khổ diệt.", "sourceRefs": [ref(DUYEN, 7)]},
        {"id": "M8_R15", "front": "Căn gốc của Vô minh là tâm sở nào?", "back": "Tâm sở Si (Moha) — luôn có mặt trong mọi tâm bất thiện.", "sourceRefs": [ref(DUYEN, 7)]},
        {"id": "M8_R16", "front": "Pháp bản thể của Hành là gì?", "back": "Tâm sở Tư (Cetanā), một trong 7 tâm sở biến hành.", "sourceRefs": [ref(DUYEN, 8)]},
        {"id": "M8_R17", "front": "Ba loại Hành là gì?", "back": "Phi phúc hành (12 tâm Bất thiện), Phúc hành (8 Thiện Dục giới + 5 Thiện Sắc giới), Bất động hành (4 Thiện Vô sắc giới).", "sourceRefs": [ref(DUYEN, 8)]},
        {"id": "M8_R18", "front": "Bất động hành (Āneñjābhisaṅkhāra) tạo ra quả gì?", "back": "Các tâm Quả Vô sắc giới.", "sourceRefs": [ref(DUYEN, 8)]},
    ],
    "quizSeeds": [
        {"id": "M8_Q01", "type": "mcq", "question": "Paṭiccasamuppāda được dịch sát nghĩa là gì?", "correctAnswer": "Tùy thuộc phát sanh / Duyên khởi", "distractors": ["Duyên hệ tương quan", "Vòng luân hồi vô tận", "Định luật nghiệp báo"], "explanation": "Paṭicca: bởi vì, vì lẽ; Samuppāda: phát sanh. Paṭṭhāna mới là Duyên hệ tương quan.", "sourceRefs": [ref(DUYEN, 6)]},
        {"id": "M8_Q02", "type": "mcq", "question": "Toát yếu về Duyên (Paccaya-saṅgaha) gồm mấy phần chính?", "correctAnswer": "Hai phần: Paṭiccasamuppāda và Paṭṭhāna", "distractors": ["Ba phần: Nghiệp, Duyên, Quả", "Bốn phần theo bốn thời", "Một phần duy nhất là 12 chi"], "explanation": "Paṭiccasamuppādanayo, Paṭṭhānanayo cāti paccayasaṅgaho duvidho veditabbo.", "sourceRefs": [ref(DUYEN, 3)]},
        {"id": "M8_Q03", "type": "mcq", "question": "Chi nào duyên cho Hành (Saṅkhārā)?", "correctAnswer": "Vô minh (Avijjā)", "distractors": ["Thức (Viññāṇa)", "Ái (Taṇhā)", "Thủ (Upādāna)"], "explanation": "Avijjāpaccayā saṅkhārā — Tùy thuộc nơi Vô minh phát sanh Hành.", "sourceRefs": [ref(DUYEN, 2), ref(DUYEN, 3)]},
        {"id": "M8_Q04", "type": "mcq", "question": "Chi nào phát sanh do duyên Thọ (Vedanā)?", "correctAnswer": "Ái (Taṇhā)", "distractors": ["Xúc (Phassa)", "Thủ (Upādāna)", "Hữu (Bhava)"], "explanation": "Vedanāpaccayā taṇhā — Tùy thuộc nơi Thọ phát sanh Ái.", "sourceRefs": [ref(DUYEN, 2)]},
        {"id": "M8_Q05", "type": "mcq", "question": "Chi nào đứng ngay trước Xúc (Phassa) trong chuỗi duyên khởi?", "correctAnswer": "Lục nhập (Saḷāyatana)", "distractors": ["Danh Sắc (Nāmarūpa)", "Thọ (Vedanā)", "Thức (Viññāṇa)"], "explanation": "Saḷāyatanapaccayā phasso — Tùy thuộc nơi Lục nhập phát sanh Xúc.", "sourceRefs": [ref(DUYEN, 2)]},
        {"id": "M8_Q06", "type": "mcq", "question": "Hai chi nào thuộc về thời quá khứ?", "correctAnswer": "Vô minh và Hành", "distractors": ["Sanh và Lão Tử", "Ái và Thủ", "Thức và Danh Sắc"], "explanation": "Avijjā, saṅkhārā atīto addhā — Vô minh và Hành thuộc quá khứ.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_Q07", "type": "mcq", "question": "Có bao nhiêu chi thuộc về thời hiện tại?", "correctAnswer": "8 chi", "distractors": ["2 chi", "5 chi", "12 chi"], "explanation": "Tám chi ở khoảng giữa (Thức → Hữu) thuộc thời hiện tại.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_Q08", "type": "mcq", "question": "“Vīsatākārā” trong Duyên khởi nghĩa là gì?", "correctAnswer": "Hai mươi phương cách nhân-quả", "distractors": ["Hai mươi chi phần", "Hai mươi loại duyên", "Hai mươi cõi tái sanh"], "explanation": "5 nhân quá khứ + 5 quả hiện tại + 5 nhân hiện tại + 5 quả vị lai = 20 phương cách.", "sourceRefs": [ref(DUYEN, 4)]},
        {"id": "M8_Q09", "type": "mcq", "question": "Ba chi nào hợp thành Phiền não luân (Kilesavaṭṭa)?", "correctAnswer": "Vô minh, Ái, Thủ", "distractors": ["Hành, Hữu, Sanh", "Thức, Danh Sắc, Lục nhập", "Xúc, Thọ, Ái"], "explanation": "Avijjā taṇhūpādāna ca kilesavaṭṭaṃ.", "sourceRefs": [ref(DUYEN, 5)]},
        {"id": "M8_Q10", "type": "mcq", "question": "Nghiệp luân (Kammavaṭṭa) gồm những gì?", "correctAnswer": "Hành và phần Nghiệp hữu của Hữu", "distractors": ["Vô minh và Ái", "Sanh và Lão Tử", "Thức và Danh Sắc"], "explanation": "Saṅkhārā ca kammavaṭṭaṃ, cùng kammabhava — một phần của Hữu.", "sourceRefs": [ref(DUYEN, 5)]},
        {"id": "M8_Q11", "type": "mcq", "question": "Hai nhân gốc (dve mūlāni) của vòng luân hồi là gì?", "correctAnswer": "Vô minh và Ái", "distractors": ["Tham và Sân", "Nghiệp và Quả", "Hành và Thủ"], "explanation": "Avijjātaṇhāvasena dve mūlāni ca veditabbāni.", "sourceRefs": [ref(DUYEN, 5)]},
        {"id": "M8_Q12", "type": "mcq", "question": "Theo kinh văn, Vô minh là không hiểu điều gì?", "correctAnswer": "Tứ Diệu Đế: Khổ, Khổ tập, Khổ diệt, con đường diệt khổ", "distractors": ["Không hiểu về 28 sắc pháp", "Không hiểu về lộ trình tâm", "Không hiểu về 16 loại nghiệp"], "explanation": "Sự không hiểu về Khổ, Khổ tập, Khổ diệt và Khổ diệt Hành lộ — đây gọi là Vô minh.", "sourceRefs": [ref(DUYEN, 7)]},
        {"id": "M8_Q13", "type": "mcq", "question": "Căn gốc (pháp bản thể) của Vô minh là tâm sở nào?", "correctAnswer": "Si (Moha)", "distractors": ["Tham (Lobha)", "Sân (Dosa)", "Tà kiến (Diṭṭhi)"], "explanation": "Moha chính là cội nguồn của Vô minh và luôn có mặt trong các tâm Bất thiện.", "sourceRefs": [ref(DUYEN, 7)]},
        {"id": "M8_Q14", "type": "mcq", "question": "Pháp bản thể của chi Hành (Saṅkhārā) là gì?", "correctAnswer": "Tâm sở Tư (Cetanā)", "distractors": ["Tâm sở Si (Moha)", "Tâm sở Xúc (Phassa)", "Tâm sở Nhất hành (Ekaggatā)"], "explanation": "Pháp bản thể của Hành là tâm sở Tư — trong 7 tâm sở biến hành.", "sourceRefs": [ref(DUYEN, 8)]},
        {"id": "M8_Q15", "type": "mcq", "question": "Phúc hành (Puññābhisaṅkhāra) tương ứng với những tâm nào?", "correctAnswer": "8 tâm Thiện Dục giới và 5 tâm Thiện Sắc giới", "distractors": ["12 tâm Bất thiện", "4 tâm Thiện Vô sắc giới", "8 tâm Siêu thế"], "explanation": "Tâm sở Tư đồng sanh 1 trong 8 Tâm Thiện Dục giới, 5 Thiện Sắc giới.", "sourceRefs": [ref(DUYEN, 8)]},
        {"id": "M8_Q16", "type": "mcq", "question": "Bất động hành (Āneñjābhisaṅkhāra) thuộc về tâm nào?", "correctAnswer": "4 tâm Thiện Vô sắc giới", "distractors": ["5 tâm Thiện Sắc giới", "8 tâm Đại thiện", "12 tâm Bất thiện"], "explanation": "Tâm sở Tư đồng sanh 1 trong 4 tâm Thiện Vô sắc giới, tạo ra các tâm Quả Vô sắc giới.", "sourceRefs": [ref(DUYEN, 8)]},
    ],
}
