import 'package:flutter/widgets.dart';

import '../../../core/localization/ui_locale_text.dart';
import '../../../data/models/vithi_model.dart';

/// Compact localized labels for each step in a cognitive process.
class VithiLabelMapper {
  static String localizedShortName(BuildContext context, VithiStepRole role) {
    final values = switch (role) {
      VithiStepRole.bhavangaSota => const {
          'en': 'Bhavaṅga',
          'vi': 'Hộ kiếp',
          'zh': '有分流',
          'zh_TW': '有分流',
          'hi': 'भवङ्ग',
          'my': 'ဘဝင်အယဉ်',
          'si': 'භවාංගය',
          'th': 'ภวังค์',
          'ja': '有分',
        },
      VithiStepRole.bhavangaCalana => const {
          'en': 'Bhv.\nCalana',
          'vi': 'Rúng\nđộng',
          'zh': '有分\n波动',
          'zh_TW': '有分\n波動',
          'hi': 'भवङ्ग\nचलन',
          'my': 'ဘဝင်\nလှုပ်',
          'si': 'භවාංග\nචලන',
          'th': 'ภวังค-\nจลนะ',
          'ja': '有分\n動揺',
        },
      VithiStepRole.bhavangupaccheda => const {
          'en': 'Bhv.\nCheda',
          'vi': 'Dứt\ndòng',
          'zh': '有分\n截断',
          'zh_TW': '有分\n截斷',
          'hi': 'भवङ्ग\nउच्छेद',
          'my': 'ဘဝင်\nပြတ်',
          'si': 'භවංගු-\nපච්ඡේද',
          'th': 'ภวังคุ-\nปัจเฉทะ',
          'ja': '有分\n遮断',
        },
      VithiStepRole.pancaDvaravajjana => const {
          'en': 'Pañca-dv.\nĀvajjana',
          'vi': 'Khán\nngũ môn',
          'zh': '五门\n转向',
          'zh_TW': '五門\n轉向',
          'hi': 'पञ्चद्वार-\nआवर्जन',
          'my': 'ပဉ္စဒွါရာ-\nဝဇ္ဇန်း',
          'si': 'පංචද්වාරා-\nවජ්ජන',
          'th': 'ปัญจทวาร-\nวัชชนะ',
          'ja': '五門\n引導',
        },
      VithiStepRole.dvipancaVinnana => const {
          'en': 'Dvi-pañca\nViññāṇa',
          'vi': 'Ngũ thức',
          'zh': '双五识',
          'zh_TW': '雙五識',
          'hi': 'द्विपञ्च-\nविज्ञान',
          'my': 'ဒွေပဉ္စ\nဝိညာဉ်',
          'si': 'ද්විපංච-\nවිඥාන',
          'th': 'ทวิปัญจ-\nวิญญาณ',
          'ja': '二回\n五識',
        },
      VithiStepRole.sampatiCchana => const {
          'en': 'Sampaṭi-\ncchana',
          'vi': 'Tiếp thâu',
          'zh': '领受',
          'zh_TW': '領受',
          'hi': 'सम्पटि-\nच्छन',
          'my': 'သမ္ပဋိ-\nစ္ဆိုင်း',
          'si': 'සම්පටි-\nච්ඡන',
          'th': 'สัมปฏิจ-\nฉันนะ',
          'ja': '受容',
        },
      VithiStepRole.santiRana => const {
          'en': 'Santīraṇa',
          'vi': 'Quan sát',
          'zh': '推度',
          'zh_TW': '推度',
          'hi': 'सन्तिरण',
          'my': 'သန္တီရဏ',
          'si': 'සන්තීරණ',
          'th': 'สันตีรณะ',
          'ja': '推度',
        },
      VithiStepRole.vottHapana => const {
          'en': 'Voṭṭhapana',
          'vi': 'Đoán định',
          'zh': '确定',
          'zh_TW': '確定',
          'hi': 'वोट्ठपन',
          'my': 'ဝုဋ္ဌော',
          'si': 'වොට්ඨපන',
          'th': 'โวฏฐัพพนะ',
          'ja': '決定',
        },
      VithiStepRole.javana => const {
          'en': 'Javana',
          'vi': 'Đổng lực',
          'zh': '速行',
          'zh_TW': '速行',
          'hi': 'जवन',
          'my': 'ဇော',
          'si': 'ජවන',
          'th': 'ชวนะ',
          'ja': '速行',
        },
      VithiStepRole.tadAramana => const {
          'en': 'Tadā-\nrammaṇa',
          'vi': 'Thập di',
          'zh': '彼所缘',
          'zh_TW': '彼所緣',
          'hi': 'तदालम्बन',
          'my': 'တဒါရုံ',
          'si': 'තදාරම්මණ',
          'th': 'ตทาลัมพนะ',
          'ja': '登録',
        },
      VithiStepRole.manoDvaravajjana => const {
          'en': 'Mano-dv.\nĀvajjana',
          'vi': 'Khán\ný môn',
          'zh': '意门\n转向',
          'zh_TW': '意門\n轉向',
          'hi': 'मनोद्वार-\nआवर्जन',
          'my': 'မနောဒွါရာ-\nဝဇ္ဇန်း',
          'si': 'මනෝද්වාරා-\nවජ්ජන',
          'th': 'มโนทวาร-\nวัชชนะ',
          'ja': '意門\n引導',
        },
      VithiStepRole.patisandhi => const {
          'en': 'Paṭisandhi',
          'vi': 'Tái sanh',
          'zh': '结生',
          'zh_TW': '結生',
          'hi': 'प्रतिसन्धि',
          'my': 'ပဋိသန္ဓေ',
          'si': 'ප්‍රතිසන්ධි',
          'th': 'ปฏิสนธิ',
          'ja': '結生',
        },
      VithiStepRole.cuti => const {
          'en': 'Cuti',
          'vi': 'Tử',
          'zh': '死心',
          'zh_TW': '死心',
          'hi': 'च्युति',
          'my': 'စုတိ',
          'si': 'චුති',
          'th': 'จุติ',
          'ja': '死心',
        },
    };
    return localizedUiText(context, values);
  }

  static String shortNameForRole(VithiStepRole role) => switch (role) {
        VithiStepRole.bhavangaSota => 'Bhavaṅga',
        VithiStepRole.bhavangaCalana => 'Bhv.\nCalana',
        VithiStepRole.bhavangupaccheda => 'Bhv.\nCheda',
        VithiStepRole.pancaDvaravajjana => 'Pañca-dv.\nĀvajjana',
        VithiStepRole.dvipancaVinnana => 'Dvi-pañca\nViññāṇa',
        VithiStepRole.sampatiCchana => 'Sampaṭi-\ncchana',
        VithiStepRole.santiRana => 'Santīraṇa',
        VithiStepRole.vottHapana => 'Voṭṭhapana',
        VithiStepRole.javana => 'Javana',
        VithiStepRole.tadAramana => 'Tadā-\nrammaṇa',
        VithiStepRole.manoDvaravajjana => 'Mano-dv.\nĀvajjana',
        VithiStepRole.patisandhi => 'Paṭisandhi',
        VithiStepRole.cuti => 'Cuti',
      };

  static String symbolForRole(VithiStepRole role) => switch (role) {
        VithiStepRole.bhavangaSota => '〜',
        VithiStepRole.bhavangaCalana => '〰',
        VithiStepRole.bhavangupaccheda => '✂',
        VithiStepRole.pancaDvaravajjana => '👁',
        VithiStepRole.dvipancaVinnana => '📡',
        VithiStepRole.sampatiCchana => '📥',
        VithiStepRole.santiRana => '🔍',
        VithiStepRole.vottHapana => '⚖',
        VithiStepRole.javana => '⚡',
        VithiStepRole.tadAramana => '🌊',
        VithiStepRole.manoDvaravajjana => '🧠',
        VithiStepRole.patisandhi => '🌱',
        VithiStepRole.cuti => '🕊',
      };
}
