import 'package:flutter/material.dart';

import '../../../core/localization/ui_locale_text.dart';
import '../../../data/models/vithi_model.dart';

/// Small interface copy used only by the Mind Process player.
///
/// Entity content remains in the offline content catalog. These labels are
/// feature-local UI controls, so they follow the selected interface locale and
/// cover every supported app language instead of falling back to English or
/// Vietnamese.
class VithiUiText {
  const VithiUiText._();

  static String _t(BuildContext context, Map<String, String> values) =>
      localizedUiText(context, values);

  static String processPicker(BuildContext context) => _t(context, const {
        'en': 'Choose a cognitive process',
        'vi': 'Chọn loại lộ trình',
        'zh': '选择一个心路过程',
        'zh_TW': '選擇一個心路過程',
        'hi': 'चित्त प्रक्रिया चुनें',
        'my': 'စိတ်အစဉ်တစ်ခုကို ရွေးပါ',
        'si': 'චිත්ත වීථියක් තෝරන්න',
        'ar': 'اختر عملية ذهنية',
        'bn': 'একটি চিত্ত-প্রক্রিয়া বেছে নিন',
        'bo': 'སེམས་ཀྱི་རྒྱུན་རིམ་ཞིག་འདེམས།',
        'de': 'Einen kognitiven Prozess wählen',
        'es': 'Elegir un proceso cognitivo',
        'fr': 'Choisir un processus cognitif',
        'id': 'Pilih proses batin',
        'it': 'Scegli un processo cognitivo',
        'ja': '心路過程を選択',
        'km': 'ជ្រើសរើសដំណើរចិត្ត',
        'ko': '마음 과정을 선택',
        'lo': 'ເລືອກຂະບວນຈິດ',
        'mn': 'Сэтгэлийн явцыг сонгох',
        'mr': 'चित्त-प्रक्रिया निवडा',
        'pt': 'Escolher um processo cognitivo',
        'ru': 'Выберите процесс сознания',
        'ta': 'சித்த செயல்முறையைத் தேர்ந்தெடுக்கவும்',
        'te': 'చిత్త ప్రక్రియను ఎంచుకోండి',
        'th': 'เลือกวิถีจิต',
      });

  static String processLabel(BuildContext context, VithiModel vithi) {
    final values = switch (vithi.vithiType) {
      VithiType.atimahanta => const {
          'en': 'Very great object',
          'vi': 'Cảnh rất lớn',
          'zh': '极大所缘',
          'zh_TW': '極大所緣',
          'hi': 'अति महान् आलंबन',
          'my': 'အလွန်ကြီးမားသော အာရုံ',
          'si': 'ඉතා මහත් ආරම්මණය',
          'ar': 'موضوع عظيم جدًا',
          'bn': 'অতি মহান বস্তু',
          'bo': 'ཡུལ་ཆེན་པོ་ཤིན་ཏུ།',
          'de': 'Sehr großes Objekt',
          'es': 'Objeto muy grande',
          'fr': 'Objet très grand',
          'id': 'Objek sangat besar',
          'it': 'Oggetto molto grande',
          'ja': '極大所縁',
          'km': 'អារម្មណ៍ធំខ្លាំង',
          'ko': '매우 큰 대상',
          'lo': 'ອາລົມໃຫຍ່ຫຼາຍ',
          'mn': 'Маш их объект',
          'mr': 'अतिशय महान आलंबन',
          'pt': 'Objeto muito grande',
          'ru': 'Очень великий объект',
          'ta': 'மிகப் பெரிய ஆரம்மணம்',
          'te': 'అతి మహత్తర ఆరమ్మణం',
          'th': 'อารมณ์ใหญ่มาก',
        },
      VithiType.mahanta => const {
          'en': 'Great object',
          'vi': 'Cảnh lớn',
          'zh': '大所缘',
          'zh_TW': '大所緣',
          'hi': 'महान् आलंबन',
          'my': 'ကြီးမားသော အာရုံ',
          'si': 'මහත් ආරම්මණය',
          'ar': 'موضوع عظيم',
          'bn': 'মহান বস্তু',
          'bo': 'ཡུལ་ཆེན་པོ།',
          'de': 'Großes Objekt',
          'es': 'Objeto grande',
          'fr': 'Grand objet',
          'id': 'Objek besar',
          'it': 'Oggetto grande',
          'ja': '大所縁',
          'km': 'អារម្មណ៍ធំ',
          'ko': '큰 대상',
          'lo': 'ອາລົມໃຫຍ່',
          'mn': 'Их объект',
          'mr': 'महान आलंबन',
          'pt': 'Objeto grande',
          'ru': 'Великий объект',
          'ta': 'பெரிய ஆரம்மணம்',
          'te': 'మహత్తర ఆరమ్మణం',
          'th': 'อารมณ์ใหญ่',
        },
      VithiType.manoVithi => const {
          'en': 'Mind door',
          'vi': 'Ý môn',
          'zh': '意门',
          'zh_TW': '意門',
          'hi': 'मन-द्वार',
          'my': 'မနောဒွါရ',
          'si': 'මනෝද්වාර',
          'ar': 'باب الذهن',
          'bn': 'মন-দ্বার',
          'bo': 'ཡིད་སྒོ།',
          'de': 'Geisttor',
          'es': 'Puerta mental',
          'fr': 'Porte mentale',
          'id': 'Pintu batin',
          'it': 'Porta mentale',
          'ja': '意門',
          'km': 'ទ្វារចិត្ត',
          'ko': '의문',
          'lo': 'ປະຕູໃຈ',
          'mn': 'Оюун хаалга',
          'mr': 'मन-द्वार',
          'pt': 'Porta mental',
          'ru': 'Дверь ума',
          'ta': 'மனக் கதவு',
          'te': 'మనో ద్వారం',
          'th': 'มโนทวาร',
        },
      VithiType.vithimutta => const {
          'en': 'Process-free',
          'vi': 'Ngoài lộ',
          'zh': '离路',
          'zh_TW': '離路',
          'hi': 'प्रक्रिया-रहित',
          'my': 'ဝီထိမုတ္တ',
          'si': 'වීථිමුත්ත',
          'ar': 'خارج العملية',
          'bn': 'প্রক্রিয়ার বাইরে',
          'bo': 'རིམ་ལས་འདས་པ།',
          'de': 'Prozessfrei',
          'es': 'Fuera del proceso',
          'fr': 'Hors processus',
          'id': 'Di luar proses',
          'it': 'Fuori processo',
          'ja': '離路',
          'km': 'ក្រៅលំដាប់',
          'ko': '과정 밖',
          'lo': 'ນອກຂະບວນ',
          'mn': 'Явцаас гадуур',
          'mr': 'प्रक्रियेबाह्य',
          'pt': 'Fora do processo',
          'ru': 'Вне процесса',
          'ta': 'செயல்முறைக்கு வெளியே',
          'te': 'ప్రక్రియకు వెలుపల',
          'th': 'พ้นวิถี',
        },
      VithiType.paritta => const {
          'en': 'Small object',
          'vi': 'Cảnh nhỏ',
          'zh': '小所缘',
          'zh_TW': '小所緣',
          'hi': 'छोटा आलंबन',
          'my': 'သေးသော အာရုံ',
          'si': 'කුඩා ආරම්මණය',
          'ar': 'موضوع صغير',
          'bn': 'ছোট বস্তু',
          'bo': 'ཡུལ་ཆུང་ངུ།',
          'de': 'Kleines Objekt',
          'es': 'Objeto pequeño',
          'fr': 'Petit objet',
          'id': 'Objek kecil',
          'it': 'Oggetto piccolo',
          'ja': '小所縁',
          'km': 'អារម្មណ៍តូច',
          'ko': '작은 대상',
          'lo': 'ອາລົມນ້ອຍ',
          'mn': 'Жижиг объект',
          'mr': 'लहान आलंबन',
          'pt': 'Objeto pequeno',
          'ru': 'Малый объект',
          'ta': 'சிறிய ஆரம்மணம்',
          'te': 'చిన్న ఆరమ్మణం',
          'th': 'อารมณ์เล็ก',
        },
      VithiType.atiparitta => const {
          'en': 'Very small object',
          'vi': 'Cảnh rất nhỏ',
          'zh': '极小所缘',
          'zh_TW': '極小所緣',
          'hi': 'अति छोटा आलंबन',
          'my': 'အလွန်သေးသော အာရုံ',
          'si': 'ඉතා කුඩා ආරම්මණය',
          'ar': 'موضوع صغير جدًا',
          'bn': 'অতি ছোট বস্তু',
          'bo': 'ཡུལ་ཆུང་ངུ་ཤིན་ཏུ།',
          'de': 'Sehr kleines Objekt',
          'es': 'Objeto muy pequeño',
          'fr': 'Objet très petit',
          'id': 'Objek sangat kecil',
          'it': 'Oggetto molto piccolo',
          'ja': '極小所縁',
          'km': 'អារម្មណ៍តូចខ្លាំង',
          'ko': '매우 작은 대상',
          'lo': 'ອາລົມນ້ອຍຫຼາຍ',
          'mn': 'Маш жижиг объект',
          'mr': 'अतिशय लहान आलंबन',
          'pt': 'Objeto muito pequeno',
          'ru': 'Очень малый объект',
          'ta': 'மிகச் சிறிய ஆரம்மணம்',
          'te': 'అతి చిన్న ఆరమ్మణం',
          'th': 'อารมณ์เล็กมาก',
        },
      VithiType.appana => const {
          'en': 'Absorption',
          'vi': 'Đắc thiền',
          'zh': '安止',
          'zh_TW': '安止',
          'hi': 'अप्पना',
          'my': 'အပ္ပနာ',
          'si': 'අප්පනා',
          'ar': 'استغراق',
          'bn': 'আপ্পনা',
          'bo': 'མཉམ་གཞག',
          'de': 'Vertiefung',
          'es': 'Absorción',
          'fr': 'Absorption',
          'id': 'Appanā',
          'it': 'Assorbimento',
          'ja': '安止',
          'km': 'អប្បនា',
          'ko': '안지',
          'lo': 'ອັບປະນາ',
          'mn': 'Шингээлт',
          'mr': 'अप्पना',
          'pt': 'Absorção',
          'ru': 'Поглощение',
          'ta': 'அப்பனா',
          'te': 'అప్పనా',
          'th': 'อัปปนา',
        },
      VithiType.lokuttara => const {
          'en': 'Supramundane',
          'vi': 'Siêu thế',
          'zh': '出世间',
          'zh_TW': '出世間',
          'hi': 'लोकुत्तर',
          'my': 'လောကုတ္တရာ',
          'si': 'ලෝකෝත්තර',
          'ar': 'فوق دنيوي',
          'bn': 'লোকোত্তর',
          'bo': 'འཇིག་རྟེན་ལས་འདས་པ།',
          'de': 'Überweltlich',
          'es': 'Supramundano',
          'fr': 'Supramondain',
          'id': 'Lokuttara',
          'it': 'Sopramondano',
          'ja': '出世間',
          'km': 'លោកុត្តរ',
          'ko': '출세간',
          'lo': 'ໂລກຸດຕະຣະ',
          'mn': 'Ертөнцөөс давсан',
          'mr': 'लोकुत्तर',
          'pt': 'Supramundano',
          'ru': 'Надмирское',
          'ta': 'லோகுத்தர',
          'te': 'లోకుత్తర',
          'th': 'โลกุตตระ',
        },
    };
    return _t(context, values);
  }

  static String doorLabel(BuildContext context, VithiModel vithi) {
    final values = switch (vithi.dvara) {
      VithiDvara.panca => const {
          'en': 'Five-door',
          'vi': 'Ngũ môn',
          'zh': '五门',
          'zh_TW': '五門',
          'hi': 'पाँच-द्वार',
          'my': 'ဒွါရငါးပါး',
          'si': 'පංචද්වාර',
          'ar': 'الأبواب الخمسة',
          'bn': 'পাঁচ-দ্বার',
          'bo': 'སྒོ་ལྔ།',
          'de': 'Fünf-Tore',
          'es': 'Cinco puertas',
          'fr': 'Cinq portes',
          'id': 'Lima pintu',
          'it': 'Cinque porte',
          'ja': '五門',
          'km': 'ទ្វារប្រាំ',
          'ko': '오문',
          'lo': 'ຫ້າປະຕູ',
          'mn': 'Таван хаалга',
          'mr': 'पाच-द्वार',
          'pt': 'Cinco portas',
          'ru': 'Пять дверей',
          'ta': 'ஐந்து கதவுகள்',
          'te': 'ఐదు ద్వారాలు',
          'th': 'ปัญจทวาร',
        },
      VithiDvara.mano => const {
          'en': 'Mind-door',
          'vi': 'Ý môn',
          'zh': '意门',
          'zh_TW': '意門',
          'hi': 'मन-द्वार',
          'my': 'မနောဒွါရ',
          'si': 'මනෝද්වාර',
          'ar': 'باب الذهن',
          'bn': 'মন-দ্বার',
          'bo': 'ཡིད་སྒོ།',
          'de': 'Geisttor',
          'es': 'Puerta mental',
          'fr': 'Porte mentale',
          'id': 'Pintu batin',
          'it': 'Porta mentale',
          'ja': '意門',
          'km': 'ទ្វារចិត្ត',
          'ko': '의문',
          'lo': 'ປະຕູໃຈ',
          'mn': 'Оюун хаалга',
          'mr': 'मन-द्वार',
          'pt': 'Porta mental',
          'ru': 'Дверь ума',
          'ta': 'மனக் கதவு',
          'te': 'మనో ద్వారం',
          'th': 'มโนทวาร',
        },
      VithiDvara.vithimutta => const {
          'en': 'Process-free',
          'vi': 'Ngoài lộ',
          'zh': '离路',
          'zh_TW': '離路',
          'hi': 'प्रक्रिया-रहित',
          'my': 'ဝီထိမုတ္တ',
          'si': 'වීථිමුත්ත',
          'ar': 'خارج العملية',
          'bn': 'প্রক্রিয়ার বাইরে',
          'bo': 'རིམ་ལས་འདས་པ།',
          'de': 'Prozessfrei',
          'es': 'Fuera del proceso',
          'fr': 'Hors processus',
          'id': 'Di luar proses',
          'it': 'Fuori processo',
          'ja': '離路',
          'km': 'ក្រៅលំដាប់',
          'ko': '과정 밖',
          'lo': 'ນອກຂະບວນ',
          'mn': 'Явцаас гадуур',
          'mr': 'प्रक्रियेबाह्य',
          'pt': 'Fora do processo',
          'ru': 'Вне процесса',
          'ta': 'செயல்முறைக்கு வெளியே',
          'te': 'ప్రక్రియకు వెలుపల',
          'th': 'พ้นวิถี',
        },
    };
    return _t(context, values);
  }

  static String momentCount(BuildContext context, int count) =>
      _t(context, const {
        'en': '{count} illustrated moments',
        'vi': '{count} sát-na minh họa',
        'zh': '{count} 个示例心识刹那',
        'zh_TW': '{count} 個示例心識剎那',
        'hi': '{count} चित्रित क्षण',
        'my': 'ပြထားသော စိတ်ခဏ {count} ခု',
        'si': 'නිරූපිත චිත්තක්ෂණ {count}',
        'ar': '{count} لحظات موضحة',
        'bn': '{count}টি চিত্রিত ক্ষণ',
        'bo': 'མཚོན་པའི་སྐད་ཅིག་ {count}',
        'de': '{count} veranschaulichte Momente',
        'es': '{count} momentos ilustrados',
        'fr': '{count} moments illustrés',
        'id': '{count} momen bergambar',
        'it': '{count} momenti illustrati',
        'ja': '{count} 個の例示刹那',
        'km': 'ខណៈចិត្តបង្ហាញ {count}',
        'ko': '도해된 순간 {count}개',
        'lo': '{count} ຂະນະທີ່ສະແດງ',
        'mn': '{count} дүрсэлсэн агшин',
        'mr': '{count} दाखवलेले क्षण',
        'pt': '{count} momentos ilustrados',
        'ru': '{count} показанных моментов',
        'ta': '{count} விளக்கப்பட்ட கணங்கள்',
        'te': '{count} చూపిన క్షణాలు',
        'th': '{count} ขณะตัวอย่าง',
      }).replaceAll('{count}', '$count');

  static String timelineTitle(BuildContext context) => _t(context, const {
        'en': 'Sequence of moments',
        'vi': 'Diễn tiến sát-na',
        'zh': '刹那次第',
        'zh_TW': '剎那次第',
        'hi': 'क्षणों का क्रम',
        'my': 'စိတ်ခဏအစဉ်',
        'si': 'චිත්තක්ෂණ අනුපිළිවෙල',
        'ar': 'تسلسل اللحظات',
        'bn': 'ক্ষণসমূহের ক্রম',
        'bo': 'སྐད་ཅིག་གི་རིམ་པ།',
        'de': 'Abfolge der Momente',
        'es': 'Secuencia de momentos',
        'fr': 'Séquence des moments',
        'id': 'Urutan momen',
        'it': 'Sequenza dei momenti',
        'ja': '刹那の連なり',
        'km': 'លំដាប់ខណៈចិត្ត',
        'ko': '순간의 순서',
        'lo': 'ລຳດັບຂອງຂະນະ',
        'mn': 'Агшнуудын дараалал',
        'mr': 'क्षणांचा क्रम',
        'pt': 'Sequência de momentos',
        'ru': 'Последовательность моментов',
        'ta': 'கணங்களின் வரிசை',
        'te': 'క్షణాల క్రమం',
        'th': 'ลำดับขณะ',
      });

  static String timelineInstruction(BuildContext context) => _t(context, const {
        'en': 'Tap a tile to study its function; swipe sideways to follow the whole process.',
        'vi': 'Chạm một ô để xem phận sự; vuốt ngang để theo dõi toàn lộ.',
        'zh': '点按方块学习其作用；横向滑动可查看整个过程。',
        'zh_TW': '點按方塊學習其作用；橫向滑動可查看整個過程。',
        'hi': 'कार्य देखने के लिए किसी खंड को टैप करें; पूरी प्रक्रिया देखने के लिए बगल में स्वाइप करें।',
        'my': 'လုပ်ငန်းကို လေ့လာရန် အကွက်ကို နှိပ်ပါ။ လုပ်ငန်းစဉ်တစ်ခုလုံးကို ကြည့်ရန် ဘေးသို့ ပွတ်ဆွဲပါ။',
        'si': 'කාර්යය බැලීමට කොටුවක් තට්ටු කරන්න; සම්පූර්ණ ක්‍රියාවලිය බලීමට පැත්තට ස්වයිප් කරන්න.',
        'ar': 'اضغط على مربع لدراسة وظيفته؛ مرّر جانبياً لمتابعة العملية كلها.',
        'bn': 'তার কাজ দেখতে একটি ঘর চাপুন; পুরো প্রক্রিয়া দেখতে পাশে সোয়াইপ করুন।',
        'bo': 'བྱེད་ལས་ལ་ལྟ་བར་སྒྲོམ་ལ་རེག རིམ་པ་ཆ་ཚང་ལ་ལྟ་བར་གཡས་གཡོན་དུ་འདྲུད།',
        'de': 'Tippe auf ein Feld, um seine Funktion zu lernen; wische seitlich für den ganzen Ablauf.',
        'es': 'Toca una ficha para estudiar su función; desliza de lado para seguir todo el proceso.',
        'fr': 'Touchez une case pour étudier sa fonction ; balayez latéralement pour suivre tout le processus.',
        'id': 'Ketuk ubin untuk mempelajari fungsinya; geser ke samping untuk mengikuti seluruh proses.',
        'it': 'Tocca una tessera per studiarne la funzione; scorri lateralmente per seguire l’intero processo.',
        'ja': 'タイルをタップして働きを学び、横にスワイプして全体の流れを追います。',
        'km': 'ប៉ះក្រឡាដើម្បីមើលមុខងារ; អូសផ្ដេកដើម្បីតាមដានដំណើរទាំងមូល។',
        'ko': '타일을 눌러 기능을 보고, 옆으로 밀어 전체 과정을 따라가세요.',
        'lo': 'ແຕະກ່ອງເພື່ອສຶກສາໜ້າທີ່; ປັດຂ້າງເພື່ອຕາມຂະບວນທັງໝົດ.',
        'mn': 'Үүргийг нь судлахын тулд нүдийг товш; бүх явцыг дагахын тулд хажуу тийш шудар.',
        'mr': 'कार्य पाहण्यासाठी चौकोनावर टॅप करा; संपूर्ण प्रक्रिया पाहण्यासाठी बाजूला स्वाइप करा.',
        'pt': 'Toque em um bloco para estudar sua função; deslize para o lado para acompanhar todo o processo.',
        'ru': 'Коснитесь плитки, чтобы изучить её функцию; проведите вбок, чтобы увидеть весь процесс.',
        'ta': 'அதன் செயலை அறிய ஓர் கட்டத்தைத் தட்டவும்; முழு செயல்முறையைப் பின்தொடர பக்கமாக இழுக்கவும்.',
        'te': 'దాని పనిని చూడటానికి గడియను తాకండి; మొత్తం ప్రక్రియను అనుసరించడానికి పక్కకు స్వైప్ చేయండి.',
        'th': 'แตะช่องเพื่อศึกษาหน้าที่; ปัดด้านข้างเพื่อติดตามทั้งกระบวน',
      });

  static String momentProgress(BuildContext context, int position, int total) =>
      _t(context, const {
        'en': 'Moment {position} / {total}',
        'vi': 'Sát-na {position} / {total}',
        'zh': '第 {position} / {total} 刹那',
        'zh_TW': '第 {position} / {total} 剎那',
        'hi': 'क्षण {position} / {total}',
        'my': 'စိတ်ခဏ {position} / {total}',
        'si': 'චිත්තක්ෂණ {position} / {total}',
        'ar': 'اللحظة {position} / {total}',
        'bn': 'ক্ষণ {position} / {total}',
        'bo': 'སྐད་ཅིག {position} / {total}',
        'de': 'Moment {position} / {total}',
        'es': 'Momento {position} / {total}',
        'fr': 'Moment {position} / {total}',
        'id': 'Momen {position} / {total}',
        'it': 'Momento {position} / {total}',
        'ja': '刹那 {position} / {total}',
        'km': 'ខណៈ {position} / {total}',
        'ko': '순간 {position} / {total}',
        'lo': 'ຂະນະ {position} / {total}',
        'mn': 'Агшин {position} / {total}',
        'mr': 'क्षण {position} / {total}',
        'pt': 'Momento {position} / {total}',
        'ru': 'Момент {position} / {total}',
        'ta': 'கணம் {position} / {total}',
        'te': 'క్షణం {position} / {total}',
        'th': 'ขณะ {position} / {total}',
      }).replaceAll('{position}', '$position').replaceAll('{total}', '$total');

  static String currentMoment(BuildContext context) => _t(context, const {
        'en': 'Current moment',
        'vi': 'Sát-na đang xem',
        'zh': '当前刹那',
        'zh_TW': '目前剎那',
        'hi': 'वर्तमान क्षण',
        'my': 'လက်ရှိစိတ်ခဏ',
        'si': 'වත්මන් චිත්තක්ෂණය',
        'ar': 'اللحظة الحالية',
        'bn': 'বর্তমান ক্ষণ',
        'bo': 'ད་ལྟའི་སྐད་ཅིག',
        'de': 'Aktueller Moment',
        'es': 'Momento actual',
        'fr': 'Moment actuel',
        'id': 'Momen saat ini',
        'it': 'Momento attuale',
        'ja': '現在の刹那',
        'km': 'ខណៈបច្ចុប្បន្ន',
        'ko': '현재 순간',
        'lo': 'ຂະນະປັດຈຸບັນ',
        'mn': 'Одоогийн агшин',
        'mr': 'सध्याचा क्षण',
        'pt': 'Momento atual',
        'ru': 'Текущий момент',
        'ta': 'தற்போதைய கணம்',
        'te': 'ప్రస్తుత క్షణం',
        'th': 'ขณะปัจจุบัน',
      });

  static String repeatLabel(BuildContext context, int occurrence, int total) =>
      _t(context, const {
        'en': 'Occurrence {occurrence} of {total}',
        'vi': 'Lần {occurrence} trong {total}',
        'zh': '第 {occurrence} 次，共 {total} 次',
        'zh_TW': '第 {occurrence} 次，共 {total} 次',
        'hi': '{total} में {occurrence}वीं बार',
        'my': '{total} ကြိမ်ထဲမှ {occurrence} ကြိမ်မြောက်',
        'si': '{total} අතර {occurrence} වැනි අවස්ථාව',
        'ar': 'التكرار {occurrence} من {total}',
        'bn': '{total}টির মধ্যে {occurrence}তম',
        'bo': '{total} ནས་ {occurrence} པ།',
        'de': 'Auftreten {occurrence} von {total}',
        'es': 'Aparición {occurrence} de {total}',
        'fr': 'Occurrence {occurrence} sur {total}',
        'id': 'Kemunculan {occurrence} dari {total}',
        'it': 'Occorrenza {occurrence} di {total}',
        'ja': '{total} 回中 {occurrence} 回目',
        'km': 'លើកទី {occurrence} ក្នុង {total}',
        'ko': '{total}회 중 {occurrence}회',
        'lo': 'ຄັ້ງທີ {occurrence} ໃນ {total}',
        'mn': '{total}-аас {occurrence} дахь',
        'mr': '{total} पैकी {occurrence} वी वेळ',
        'pt': 'Ocorrência {occurrence} de {total}',
        'ru': 'Повтор {occurrence} из {total}',
        'ta': '{total} இல் {occurrence}வது நிகழ்வு',
        'te': '{total}లో {occurrence}వ సంభవం',
        'th': 'ครั้งที่ {occurrence} จาก {total}',
      }).replaceAll('{occurrence}', '$occurrence').replaceAll('{total}', '$total');

  static String optional(BuildContext context) => _t(context, const {
        'en': 'Optional',
        'vi': 'Tùy chọn',
        'zh': '可选',
        'zh_TW': '可選',
        'hi': 'वैकल्पिक',
        'my': 'ရွေးချယ်နိုင်',
        'si': 'විකල්ප',
        'ar': 'اختياري',
        'bn': 'ঐচ্ছিক',
        'bo': 'གདམ་ཁ།',
        'de': 'Optional',
        'es': 'Opcional',
        'fr': 'Facultatif',
        'id': 'Opsional',
        'it': 'Facoltativo',
        'ja': '任意',
        'km': 'ជាជម្រើស',
        'ko': '선택',
        'lo': 'ເລືອກໄດ້',
        'mn': 'Сонголттой',
        'mr': 'ऐच्छिक',
        'pt': 'Opcional',
        'ru': 'Необязательно',
        'ta': 'விருப்பம்',
        'te': 'ఐచ్ఛికం',
        'th': 'ไม่บังคับ',
      });

  static String possibleCittas(BuildContext context, int count) =>
      _t(context, const {
        'en': 'Possible cittas ({count})',
        'vi': 'Tâm có thể sanh ({count})',
        'zh': '可能生起的心 ({count})',
        'zh_TW': '可能生起的心 ({count})',
        'hi': 'संभावित चित्त ({count})',
        'my': 'ဖြစ်နိုင်သော စိတ်များ ({count})',
        'si': 'ඇතිවිය හැකි චිත්ත ({count})',
        'ar': 'الذهنات الممكنة ({count})',
        'bn': 'সম্ভাব্য চিত্ত ({count})',
        'bo': 'འབྱུང་སྲིད་པའི་སེམས། ({count})',
        'de': 'Mögliche Cittas ({count})',
        'es': 'Cittas posibles ({count})',
        'fr': 'Cittas possibles ({count})',
        'id': 'Citta yang mungkin ({count})',
        'it': 'Citta possibili ({count})',
        'ja': '生起し得る心 ({count})',
        'km': 'ចិត្តអាចកើត ({count})',
        'ko': '가능한 마음 ({count})',
        'lo': 'ຈິດທີ່ເປັນໄປໄດ້ ({count})',
        'mn': 'Боломжит читта ({count})',
        'mr': 'संभाव्य चित्त ({count})',
        'pt': 'Cittas possíveis ({count})',
        'ru': 'Возможные читты ({count})',
        'ta': 'சாத்தியமான சித்தங்கள் ({count})',
        'te': 'సంభవించే చిత్తాలు ({count})',
        'th': 'จิตที่เป็นไปได้ ({count})',
      }).replaceAll('{count}', '$count');

  static String doctrinalNote(BuildContext context) => _t(context, const {
        'en': 'Doctrinal note',
        'vi': 'Ghi chú giáo lý',
        'zh': '教义说明',
        'zh_TW': '教義說明',
        'hi': 'धम्म टिप्पणी',
        'my': 'ဓမ္မမှတ်ချက်',
        'si': 'ධර්ම සටහන',
        'ar': 'ملاحظة تعليمية',
        'bn': 'ধর্মীয় নোট',
        'bo': 'ཆོས་ཀྱི་ཟིན་ཐོ།',
        'de': 'Lehrhinweis',
        'es': 'Nota doctrinal',
        'fr': 'Note doctrinale',
        'id': 'Catatan doktrinal',
        'it': 'Nota dottrinale',
        'ja': '教理メモ',
        'km': 'កំណត់ចំណាំធម៌',
        'ko': '교리 메모',
        'lo': 'ໝາຍເຫດທາງທຳມະ',
        'mn': 'Сургаалын тэмдэглэл',
        'mr': 'धम्म नोंद',
        'pt': 'Nota doutrinal',
        'ru': 'Доктринальное примечание',
        'ta': 'தம்மக் குறிப்பு',
        'te': 'ధమ్మ గమనిక',
        'th': 'หมายเหตุธรรม',
      });

  static String backgroundTitle(BuildContext context) => _t(context, const {
        'en': 'Process context',
        'vi': 'Bối cảnh của lộ trình',
        'zh': '过程背景',
        'zh_TW': '過程背景',
        'hi': 'प्रक्रिया का संदर्भ',
        'my': 'လုပ်ငန်းစဉ်နောက်ခံ',
        'si': 'ක්‍රියාවලි පසුබිම',
        'ar': 'سياق العملية',
        'bn': 'প্রক্রিয়ার প্রেক্ষাপট',
        'bo': 'རིམ་པའི་སྐབས་དོན།',
        'de': 'Prozesskontext',
        'es': 'Contexto del proceso',
        'fr': 'Contexte du processus',
        'id': 'Konteks proses',
        'it': 'Contesto del processo',
        'ja': '過程の背景',
        'km': 'បរិបទដំណើរ',
        'ko': '과정의 맥락',
        'lo': 'ບໍລິບົດຂອງຂະບວນ',
        'mn': 'Явцын нөхцөл',
        'mr': 'प्रक्रियेचा संदर्भ',
        'pt': 'Contexto do processo',
        'ru': 'Контекст процесса',
        'ta': 'செயல்முறைப் பின்னணி',
        'te': 'ప్రక్రియ సందర్భం',
        'th': 'บริบทของวิถี',
      });

  static String arisingCondition(BuildContext context) => _t(context, const {
        'en': 'Arising condition',
        'vi': 'Điều kiện phát sinh',
        'zh': '生起条件',
        'zh_TW': '生起條件',
        'hi': 'उदय की शर्त',
        'my': 'ဖြစ်ပေါ်စေသော အခြေအနေ',
        'si': 'උදාවීමේ කොන්දේසිය',
        'ar': 'شرط النشوء',
        'bn': 'উদয়ের শর্ত',
        'bo': 'འབྱུང་རྐྱེན།',
        'de': 'Entstehungsbedingung',
        'es': 'Condición de surgimiento',
        'fr': 'Condition d’apparition',
        'id': 'Kondisi kemunculan',
        'it': 'Condizione di sorgere',
        'ja': '生起条件',
        'km': 'លក្ខខណ្ឌកើតឡើង',
        'ko': '일어남의 조건',
        'lo': 'ເງື່ອນໄຂການເກີດ',
        'mn': 'Үүсэх нөхцөл',
        'mr': 'उदयाची अट',
        'pt': 'Condição de surgimento',
        'ru': 'Условие возникновения',
        'ta': 'எழுச்சியின் நிபந்தனை',
        'te': 'ఉద్భవ పరిస్థితి',
        'th': 'ปัจจัยให้เกิด',
      });

  static String significance(BuildContext context) => _t(context, const {
        'en': 'Key point',
        'vi': 'Điểm then chốt',
        'zh': '要点',
        'zh_TW': '要點',
        'hi': 'मुख्य बिंदु',
        'my': 'အဓိကအချက်',
        'si': 'ප්‍රධාන කරුණ',
        'ar': 'النقطة الأساسية',
        'bn': 'মূল কথা',
        'bo': 'གཙོ་གནད།',
        'de': 'Kernpunkt',
        'es': 'Punto clave',
        'fr': 'Point clé',
        'id': 'Poin utama',
        'it': 'Punto chiave',
        'ja': '要点',
        'km': 'ចំណុចសំខាន់',
        'ko': '핵심점',
        'lo': 'ຈຸດສຳຄັນ',
        'mn': 'Гол санаа',
        'mr': 'मुख्य मुद्दा',
        'pt': 'Ponto-chave',
        'ru': 'Ключевой момент',
        'ta': 'முக்கிய புள்ளி',
        'te': 'ముఖ్యాంశం',
        'th': 'ประเด็นสำคัญ',
      });

  static String noCittaMapping(BuildContext context) => _t(context, const {
        'en': 'No specific citta is listed for this moment.',
        'vi': 'Dữ liệu chưa nêu tâm cụ thể cho sát-na này.',
        'zh': '此刹那未列出具体的心。',
        'zh_TW': '此剎那未列出具體的心。',
        'hi': 'इस क्षण के लिए कोई विशिष्ट चित्त सूचीबद्ध नहीं है।',
        'my': 'ဤစိတ်ခဏအတွက် သီးခြားစိတ်ကို မဖော်ပြထားပါ။',
        'si': 'මෙම චිත්තක්ෂණයට විශේෂ චිත්තයක් දක්වා නැත.',
        'ar': 'لا توجد چتة محددة لهذه اللحظة.',
        'bn': 'এই ক্ষণের জন্য নির্দিষ্ট চিত্ত দেওয়া নেই।',
        'bo': 'སྐད་ཅིག་འདིར་སེམས་ངེས་ཅན་མི་འདུག',
        'de': 'Für diesen Moment ist kein bestimmtes Citta aufgeführt.',
        'es': 'No se indica ningún citta específico para este momento.',
        'fr': 'Aucun citta précis n’est indiqué pour ce moment.',
        'id': 'Tidak ada citta khusus yang dicantumkan untuk momen ini.',
        'it': 'Nessun citta specifico è indicato per questo momento.',
        'ja': 'この刹那には特定の心が示されていません。',
        'km': 'មិនបានរាយចិត្តជាក់លាក់សម្រាប់ខណៈនេះទេ។',
        'ko': '이 순간에 대한 특정 마음이 나열되지 않았습니다.',
        'lo': 'ບໍ່ໄດ້ລະບຸຈິດສະເພາະສຳລັບຂະນະນີ້.',
        'mn': 'Энэ агшинд тодорхой читта жагсаагдаагүй.',
        'mr': 'या क्षणासाठी विशिष्ट चित्त दिलेले नाही.',
        'pt': 'Nenhum citta específico está listado para este momento.',
        'ru': 'Для этого момента конкретная читта не указана.',
        'ta': 'இந்தக் கணத்திற்கு குறிப்பிட்ட சித்தம் தரப்படவில்லை.',
        'te': 'ఈ క్షణానికి నిర్దిష్ట చిత్తం ఇవ్వబడలేదు.',
        'th': 'ยังไม่ระบุจิตเฉพาะสำหรับขณะนี้',
      });

  static String continuation(BuildContext context) => _t(context, const {
        'en': 'Returns to the Bhavaṅga stream — continuing',
        'vi': 'Trở về dòng Hộ Kiếp — tiếp diễn',
        'zh': '返回有分流 — 继续',
        'zh_TW': '返回有分流 — 繼續',
        'hi': 'भवङ्ग धारा में लौटता है — जारी',
        'my': 'ဘဝင်္ဂစီးကြောင်းသို့ ပြန်သွားသည် — ဆက်လက်',
        'si': 'භවාංග ප්‍රවාහයට ආපසු යයි — දිගටම',
        'ar': 'يعود إلى تيار بهافانغا — مستمر',
        'bn': 'ভবঙ্গ স্রোতে ফিরে যায় — চলমান',
        'bo': 'Bhavaṅga རྒྱུན་དུ་ཕྱིར་ལོག — མུ་མཐུད།',
        'de': 'Kehrt zum Bhavaṅga-Strom zurück — fortlaufend',
        'es': 'Vuelve a la corriente Bhavaṅga — continúa',
        'fr': 'Retour au courant Bhavaṅga — continuation',
        'id': 'Kembali ke arus Bhavaṅga — berlanjut',
        'it': 'Ritorna al flusso Bhavaṅga — continua',
        'ja': '有分の流れに戻る — 継続',
        'km': 'ត្រឡប់ទៅស្ទ្រីម Bhavaṅga — បន្ត',
        'ko': '바왕가 흐름으로 돌아감 — 계속',
        'lo': 'ກັບສູ່ກະແສ Bhavaṅga — ຕໍ່ເນື່ອງ',
        'mn': 'Бхаванга урсгалд буцна — үргэлжилнэ',
        'mr': 'भवंग प्रवाहात परतते — पुढे चालू',
        'pt': 'Retorna ao fluxo Bhavaṅga — continua',
        'ru': 'Возвращается к потоку бхаванги — продолжается',
        'ta': 'Bhavaṅga ஓட்டத்திற்குத் திரும்புகிறது — தொடர்கிறது',
        'te': 'Bhavaṅga ప్రవాహానికి తిరిగి వెళ్తుంది — కొనసాగుతుంది',
        'th': 'กลับสู่กระแสภวังคะ — ต่อเนื่อง',
      });

  static String play(BuildContext context) => _t(context, const {
        'en': 'Play sequence',
        'vi': 'Tự động trình diễn',
        'zh': '播放序列',
        'zh_TW': '播放序列',
        'hi': 'क्रम चलाएँ',
        'my': 'အစဉ်ကို ဖွင့်ပါ',
        'si': 'අනුපිළිවෙල ධාවනය කරන්න',
        'ar': 'تشغيل التسلسل',
        'bn': 'ক্রম চালান',
        'bo': 'རིམ་པ་གཏོང་།',
        'de': 'Sequenz abspielen',
        'es': 'Reproducir secuencia',
        'fr': 'Lire la séquence',
        'id': 'Putar urutan',
        'it': 'Riproduci sequenza',
        'ja': '順序を再生',
        'km': 'ចាក់លំដាប់',
        'ko': '순서 재생',
        'lo': 'ຫຼິ້ນລຳດັບ',
        'mn': 'Дарааллыг тоглуулах',
        'mr': 'क्रम चालू करा',
        'pt': 'Reproduzir sequência',
        'ru': 'Воспроизвести последовательность',
        'ta': 'வரிசையை இயக்கவும்',
        'te': 'క్రమాన్ని ప్లే చేయండి',
        'th': 'เล่นลำดับ',
      });

  static String pause(BuildContext context) => _t(context, const {
        'en': 'Pause sequence',
        'vi': 'Tạm dừng trình diễn',
        'zh': '暂停序列',
        'zh_TW': '暫停序列',
        'hi': 'क्रम रोकें',
        'my': 'အစဉ်ကို ခဏရပ်ပါ',
        'si': 'අනුපිළිවෙල නවත්වන්න',
        'ar': 'إيقاف التسلسل مؤقتاً',
        'bn': 'ক্রম বিরতি দিন',
        'bo': 'རིམ་པ་སྐབས་འཇོག',
        'de': 'Sequenz pausieren',
        'es': 'Pausar secuencia',
        'fr': 'Mettre la séquence en pause',
        'id': 'Jeda urutan',
        'it': 'Metti in pausa',
        'ja': '順序を一時停止',
        'km': 'ផ្អាកលំដាប់',
        'ko': '순서 일시정지',
        'lo': 'ຢຸດລຳດັບຊົ່ວຄາວ',
        'mn': 'Дарааллыг түр зогсоох',
        'mr': 'क्रम थांबवा',
        'pt': 'Pausar sequência',
        'ru': 'Приостановить последовательность',
        'ta': 'வரிசையை இடைநிறுத்தவும்',
        'te': 'క్రమాన్ని విరామం చేయండి',
        'th': 'หยุดลำดับชั่วคราว',
      });

  static String previous(BuildContext context) => _t(context, const {
        'en': 'Previous moment',
        'vi': 'Sát-na trước',
        'zh': '上一刹那',
        'zh_TW': '上一剎那',
        'hi': 'पिछला क्षण',
        'my': 'ယခင်စိတ်ခဏ',
        'si': 'පෙර චිත්තක්ෂණය',
        'ar': 'اللحظة السابقة',
        'bn': 'পূর্ববর্তী ক্ষণ',
        'bo': 'སྔོན་མའི་སྐད་ཅིག',
        'de': 'Vorheriger Moment',
        'es': 'Momento anterior',
        'fr': 'Moment précédent',
        'id': 'Momen sebelumnya',
        'it': 'Momento precedente',
        'ja': '前の刹那',
        'km': 'ខណៈមុន',
        'ko': '이전 순간',
        'lo': 'ຂະນະກ່ອນ',
        'mn': 'Өмнөх агшин',
        'mr': 'मागील क्षण',
        'pt': 'Momento anterior',
        'ru': 'Предыдущий момент',
        'ta': 'முந்தைய கணம்',
        'te': 'మునుపటి క్షణం',
        'th': 'ขณะก่อนหน้า',
      });

  static String next(BuildContext context) => _t(context, const {
        'en': 'Next moment',
        'vi': 'Sát-na tiếp theo',
        'zh': '下一刹那',
        'zh_TW': '下一剎那',
        'hi': 'अगला क्षण',
        'my': 'နောက်စိတ်ခဏ',
        'si': 'ඊළඟ චිත්තක්ෂණය',
        'ar': 'اللحظة التالية',
        'bn': 'পরবর্তী ক্ষণ',
        'bo': 'རྗེས་མའི་སྐད་ཅིག',
        'de': 'Nächster Moment',
        'es': 'Momento siguiente',
        'fr': 'Moment suivant',
        'id': 'Momen berikutnya',
        'it': 'Momento successivo',
        'ja': '次の刹那',
        'km': 'ខណៈបន្ទាប់',
        'ko': '다음 순간',
        'lo': 'ຂະນະຕໍ່ໄປ',
        'mn': 'Дараагийн агшин',
        'mr': 'पुढील क्षण',
        'pt': 'Próximo momento',
        'ru': 'Следующий момент',
        'ta': 'அடுத்த கணம்',
        'te': 'తదుపరి క్షణం',
        'th': 'ขณะถัดไป',
      });

  static String reset(BuildContext context) => _t(context, const {
        'en': 'Restart sequence',
        'vi': 'Về đầu lộ',
        'zh': '重新开始序列',
        'zh_TW': '重新開始序列',
        'hi': 'क्रम फिर शुरू करें',
        'my': 'အစဉ်ကို ပြန်စပါ',
        'si': 'අනුපිළිවෙල නැවත අරඹන්න',
        'ar': 'إعادة بدء التسلسل',
        'bn': 'ক্রম আবার শুরু করুন',
        'bo': 'རིམ་པ་བསྐྱར་འགོ་འཛུགས།',
        'de': 'Sequenz neu starten',
        'es': 'Reiniciar secuencia',
        'fr': 'Recommencer la séquence',
        'id': 'Mulai ulang urutan',
        'it': 'Riavvia sequenza',
        'ja': '順序を最初から',
        'km': 'ចាប់ផ្តើមលំដាប់ឡើងវិញ',
        'ko': '순서 다시 시작',
        'lo': 'ເລີ່ມລຳດັບໃໝ່',
        'mn': 'Дарааллыг дахин эхлүүлэх',
        'mr': 'क्रम पुन्हा सुरू करा',
        'pt': 'Reiniciar sequência',
        'ru': 'Начать последовательность заново',
        'ta': 'வரிசையை மீண்டும் தொடங்கவும்',
        'te': 'క్రమాన్ని మళ్లీ ప్రారంభించండి',
        'th': 'เริ่มลำดับใหม่',
      });

  static String timelineSemantics(
    BuildContext context,
    int count,
    String processName,
  ) => _t(context, const {
        'en': '{processName} has {count} illustrated moments. Swipe sideways to view the full sequence.',
        'vi': 'Lộ trình {processName} gồm {count} sát-na minh họa. Vuốt ngang để xem toàn bộ.',
        'zh': '{processName} 有 {count} 个示例刹那。横向滑动可查看完整序列。',
        'zh_TW': '{processName} 有 {count} 個示例剎那。橫向滑動可查看完整序列。',
        'hi': '{processName} में {count} चित्रित क्षण हैं। पूरा क्रम देखने के लिए बगल में स्वाइप करें।',
        'my': '{processName} တွင် ပြထားသော စိတ်ခဏ {count} ခုရှိသည်။ အစဉ်တစ်ခုလုံးကို ကြည့်ရန် ဘေးသို့ ပွတ်ဆွဲပါ။',
        'si': '{processName} හි නිරූපිත චිත්තක්ෂණ {count} ඇත. සම්පූර්ණ අනුපිළිවෙල බැලීමට පැත්තට ස්වයිප් කරන්න.',
        'ar': 'تحتوي {processName} على {count} لحظات موضحة. مرّر جانبياً لعرض التسلسل الكامل.',
        'bn': '{processName}-এ {count}টি চিত্রিত ক্ষণ আছে। পূর্ণ ক্রম দেখতে পাশে সোয়াইপ করুন।',
        'bo': '{processName} ལ་ {count} མཚོན་པའི་སྐད་ཅིག་ཡོད། རིམ་པ་ཆ་ཚང་ལ་ལྟ་བར་གཡས་གཡོན་འདྲུད།',
        'de': '{processName} hat {count} veranschaulichte Momente. Wische seitlich, um die ganze Sequenz zu sehen.',
        'es': '{processName} tiene {count} momentos ilustrados. Desliza de lado para ver la secuencia completa.',
        'fr': '{processName} comporte {count} moments illustrés. Balayez latéralement pour voir toute la séquence.',
        'id': '{processName} memiliki {count} momen bergambar. Geser ke samping untuk melihat seluruh urutan.',
        'it': '{processName} ha {count} momenti illustrati. Scorri lateralmente per vedere l’intera sequenza.',
        'ja': '{processName} には {count} 個の例示刹那があります。横にスワイプして全体を表示します。',
        'km': '{processName} មានខណៈបង្ហាញ {count}។ អូសផ្ដេកដើម្បីមើលលំដាប់ទាំងមូល។',
        'ko': '{processName}에는 도해된 순간 {count}개가 있습니다. 전체 순서를 보려면 옆으로 미세요.',
        'lo': '{processName} ມີ {count} ຂະນະທີ່ສະແດງ. ປັດຂ້າງເພື່ອເບິ່ງລຳດັບທັງໝົດ.',
        'mn': '{processName} нь {count} дүрсэлсэн агшинтай. Бүтэн дарааллыг харахын тулд хажуу тийш шудар.',
        'mr': '{processName} मध्ये {count} दाखवलेले क्षण आहेत. संपूर्ण क्रम पाहण्यासाठी बाजूला स्वाइप करा.',
        'pt': '{processName} tem {count} momentos ilustrados. Deslize para o lado para ver a sequência completa.',
        'ru': 'В {processName} показано {count} моментов. Проведите вбок, чтобы увидеть всю последовательность.',
        'ta': '{processName} இல் {count} விளக்கப்பட்ட கணங்கள் உள்ளன. முழு வரிசையைக் காண பக்கமாக இழுக்கவும்.',
        'te': '{processName}లో {count} చూపిన క్షణాలు ఉన్నాయి. పూర్తి క్రమాన్ని చూడటానికి పక్కకు స్వైప్ చేయండి.',
        'th': '{processName} มี {count} ขณะตัวอย่าง ปัดด้านข้างเพื่อดูทั้งลำดับ',
      })
          .replaceAll('{processName}', processName)
          .replaceAll('{count}', '$count');

  static String momentSemantics(
    BuildContext context, {
    required int position,
    required int total,
    required String name,
    required bool isSelected,
    required bool isOptional,
    required String occurrenceLabel,
  }) {
    final selected = isSelected ? ' ${_selectedSentence(context)}' : '';
    final optional = isOptional ? ' ${_optionalSentence(context)}' : '';
    final occurrence = occurrenceLabel.isEmpty ? '' : ' $occurrenceLabel.';
    return '${momentProgress(context, position, total)}: $name.$occurrence$optional$selected';
  }

  static String _selectedSentence(BuildContext context) => _t(context, const {
        'en': 'Selected.',
        'vi': 'Đang được chọn.',
        'zh': '已选择。',
        'zh_TW': '已選擇。',
        'hi': 'चयनित।',
        'my': 'ရွေးထားသည်။',
        'si': 'තෝරා ඇත.',
        'ar': 'محدد.',
        'bn': 'নির্বাচিত।',
        'bo': 'བདམས་ཟིན།',
        'de': 'Ausgewählt.',
        'es': 'Seleccionado.',
        'fr': 'Sélectionné.',
        'id': 'Dipilih.',
        'it': 'Selezionato.',
        'ja': '選択中。',
        'km': 'បានជ្រើស។',
        'ko': '선택됨.',
        'lo': 'ເລືອກແລ້ວ.',
        'mn': 'Сонгосон.',
        'mr': 'निवडलेले.',
        'pt': 'Selecionado.',
        'ru': 'Выбрано.',
        'ta': 'தேர்ந்தெடுக்கப்பட்டது.',
        'te': 'ఎంచుకున్నారు.',
        'th': 'เลือกแล้ว',
      });

  static String _optionalSentence(BuildContext context) => _t(context, const {
        'en': 'Optional.',
        'vi': 'Tùy chọn.',
        'zh': '可选。',
        'zh_TW': '可選。',
        'hi': 'वैकल्पिक।',
        'my': 'ရွေးချယ်နိုင်သည်။',
        'si': 'විකල්පයි.',
        'ar': 'اختياري.',
        'bn': 'ঐচ্ছিক।',
        'bo': 'གདམ་ཁ།',
        'de': 'Optional.',
        'es': 'Opcional.',
        'fr': 'Facultatif.',
        'id': 'Opsional.',
        'it': 'Facoltativo.',
        'ja': '任意。',
        'km': 'ជាជម្រើស។',
        'ko': '선택.',
        'lo': 'ເລືອກໄດ້.',
        'mn': 'Сонголттой.',
        'mr': 'ऐच्छिक.',
        'pt': 'Opcional.',
        'ru': 'Необязательно.',
        'ta': 'விருப்பம்.',
        'te': 'ఐచ్ఛికం.',
        'th': 'ไม่บังคับ',
      });
}
